namespace SimplePhotoViewer
{
	runtimeclass ImageSku : Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		ImageSku(Windows.Storage.FileProperties.ImageProperties imageProps, Windows.Storage.StorageFile imageFile, String name, String type, Windows.UI.Xaml.Media.Imaging.BitmapImage imageThumbnail, String nameWithType);
		ImageSku(Windows.Storage.FileProperties.ImageProperties imageProps, Windows.Storage.StorageFile imageFile, String name, String type, String nameWithType);
		ImageSku(String defaultTipString);

		Boolean ImageIsSelected{ get; set; };

		Windows.Storage.StorageFile ImageFile{ get; set; }; 
		Windows.Storage.FileProperties.ImageProperties ImageProperties{ get; };
		String ImageName{ get; set; }; 
		String ImageFileType{ get; set; };
		String ImageNameWithType{ get; set; }; 
		Windows.UI.Xaml.Media.Imaging.BitmapImage ImageThumbnail{ get; set; };
		Windows.UI.Xaml.Media.Imaging.BitmapImage ImageContent{ get; set; };
		Double RenderRotation{ get; set; };
	}
}