import "ImageSku.idl";

namespace SimplePhotoViewer
{
    runtimeclass MainPage : Windows.UI.Xaml.Controls.Page, Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
		MainPage();
        
		Windows.Foundation.Collections.IObservableVector<IInspectable> ImageSkus{get;set;};
		Windows.Foundation.Collections.IObservableVector<IInspectable> TreeViewFolders{ get; };
		Windows.Foundation.Collections.IObservableVector<IInspectable> SearchResults{ get; };

		String CurrentSelectedFolder{ get; set; };
		UInt32 CurrentFolderImageNumber{ get; };
		UInt32 CurrentFolderSelectedImageNumber{ get; };
    }
}
