// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/Windows.Storage.0.h"
#include "winrt/impl/Windows.Storage.FileProperties.0.h"
#include "winrt/impl/Windows.UI.Xaml.0.h"
#include "winrt/impl/Windows.UI.Xaml.Data.0.h"
#include "winrt/impl/Windows.UI.Xaml.Interop.0.h"
#include "winrt/impl/Windows.UI.Xaml.Markup.0.h"
#include "winrt/impl/Windows.UI.Xaml.Media.Imaging.0.h"
#include "winrt/impl/Windows.UI.Composition.0.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.0.h"
#include "winrt/impl/Windows.UI.Xaml.Media.0.h"
#include "winrt/impl/SimplePhotoViewer.0.h"

WINRT_EXPORT namespace winrt::SimplePhotoViewer {

struct WINRT_EBO IBackdropBlurBrush :
    Windows::Foundation::IInspectable,
    impl::consume_t<IBackdropBlurBrush>
{
    IBackdropBlurBrush(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IBackdropBlurBrushStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IBackdropBlurBrushStatics>
{
    IBackdropBlurBrushStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IBackdropExposureBrush :
    Windows::Foundation::IInspectable,
    impl::consume_t<IBackdropExposureBrush>
{
    IBackdropExposureBrush(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IBackdropExposureBrushStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IBackdropExposureBrushStatics>
{
    IBackdropExposureBrushStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IBackdropSaturationBrush :
    Windows::Foundation::IInspectable,
    impl::consume_t<IBackdropSaturationBrush>
{
    IBackdropSaturationBrush(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IBackdropSaturationBrushStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IBackdropSaturationBrushStatics>
{
    IBackdropSaturationBrushStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IBackdropSepiaBrush :
    Windows::Foundation::IInspectable,
    impl::consume_t<IBackdropSepiaBrush>
{
    IBackdropSepiaBrush(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IBackdropSepiaBrushStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IBackdropSepiaBrushStatics>
{
    IBackdropSepiaBrushStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IBackdropTemperatureAndTintBrush :
    Windows::Foundation::IInspectable,
    impl::consume_t<IBackdropTemperatureAndTintBrush>
{
    IBackdropTemperatureAndTintBrush(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IBackdropTemperatureAndTintBrushStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IBackdropTemperatureAndTintBrushStatics>
{
    IBackdropTemperatureAndTintBrushStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IDetailPage :
    Windows::Foundation::IInspectable,
    impl::consume_t<IDetailPage>
{
    IDetailPage(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IDirectoryItem :
    Windows::Foundation::IInspectable,
    impl::consume_t<IDirectoryItem>
{
    IDirectoryItem(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IDirectoryItemFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IDirectoryItemFactory>
{
    IDirectoryItemFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IExplorerItemTemplateSelector :
    Windows::Foundation::IInspectable,
    impl::consume_t<IExplorerItemTemplateSelector>
{
    IExplorerItemTemplateSelector(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IImageSku :
    Windows::Foundation::IInspectable,
    impl::consume_t<IImageSku>
{
    IImageSku(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IImageSkuFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IImageSkuFactory>
{
    IImageSkuFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IMainPage :
    Windows::Foundation::IInspectable,
    impl::consume_t<IMainPage>
{
    IMainPage(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IPageNavigationParameter :
    Windows::Foundation::IInspectable,
    impl::consume_t<IPageNavigationParameter>
{
    IPageNavigationParameter(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IPageNavigationParameterFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IPageNavigationParameterFactory>
{
    IPageNavigationParameterFactory(std::nullptr_t = nullptr) noexcept {}
};

}
