// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/Windows.ApplicationModel.Contacts.1.h"
#include "winrt/impl/Windows.ApplicationModel.DataTransfer.1.h"
#include "winrt/impl/Windows.Foundation.1.h"
#include "winrt/impl/Windows.UI.1.h"
#include "winrt/impl/Windows.UI.Text.1.h"
#include "winrt/impl/Windows.UI.Xaml.1.h"
#include "winrt/impl/Windows.UI.Xaml.Automation.1.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.1.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.Primitives.1.h"
#include "winrt/impl/Windows.UI.Xaml.Input.1.h"
#include "winrt/impl/Windows.UI.Xaml.Media.1.h"
#include "winrt/impl/Windows.UI.Xaml.Media.Animation.1.h"
#include "winrt/impl/Windows.Foundation.Collections.1.h"
#include "winrt/impl/Windows.UI.Composition.1.h"
#include "winrt/impl/Windows.UI.Xaml.Automation.Peers.1.h"
#include "winrt/impl/Windows.UI.Xaml.Automation.Provider.1.h"
#include "impl/Microsoft.UI.Xaml.Controls.1.h"

WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Controls {

}

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Controls {

struct WINRT_EBO BitmapIconSource :
    Microsoft::UI::Xaml::Controls::IBitmapIconSource,
    impl::base<BitmapIconSource, Microsoft::UI::Xaml::Controls::IconSource, Windows::UI::Xaml::DependencyObject>,
    impl::require<BitmapIconSource, Microsoft::UI::Xaml::Controls::IIconSource, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2>
{
    BitmapIconSource(std::nullptr_t) noexcept {}
    BitmapIconSource();
    static Windows::UI::Xaml::DependencyProperty UriSourceProperty();
    static Windows::UI::Xaml::DependencyProperty ShowAsMonochromeProperty();
};

struct WINRT_EBO ColorChangedEventArgs :
    Microsoft::UI::Xaml::Controls::IColorChangedEventArgs
{
    ColorChangedEventArgs(std::nullptr_t) noexcept {}
};

struct WINRT_EBO ColorPicker :
    Microsoft::UI::Xaml::Controls::IColorPicker,
    impl::base<ColorPicker, Windows::UI::Xaml::Controls::Control, Windows::UI::Xaml::FrameworkElement, Windows::UI::Xaml::UIElement, Windows::UI::Xaml::DependencyObject>,
    impl::require<ColorPicker, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::Controls::IControl, Windows::UI::Xaml::Controls::IControl2, Windows::UI::Xaml::Controls::IControl3, Windows::UI::Xaml::Controls::IControl4, Windows::UI::Xaml::Controls::IControl5, Windows::UI::Xaml::Controls::IControl7, Windows::UI::Xaml::Controls::IControlOverrides, Windows::UI::Xaml::Controls::IControlOverrides6, Windows::UI::Xaml::Controls::IControlProtected, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::IFrameworkElement, Windows::UI::Xaml::IFrameworkElement2, Windows::UI::Xaml::IFrameworkElement3, Windows::UI::Xaml::IFrameworkElement4, Windows::UI::Xaml::IFrameworkElement6, Windows::UI::Xaml::IFrameworkElement7, Windows::UI::Xaml::IFrameworkElementOverrides, Windows::UI::Xaml::IFrameworkElementOverrides2, Windows::UI::Xaml::IFrameworkElementProtected7, Windows::UI::Xaml::IUIElement, Windows::UI::Xaml::IUIElement2, Windows::UI::Xaml::IUIElement3, Windows::UI::Xaml::IUIElement4, Windows::UI::Xaml::IUIElement5, Windows::UI::Xaml::IUIElement7, Windows::UI::Xaml::IUIElement8, Windows::UI::Xaml::IUIElement9, Windows::UI::Xaml::IUIElementOverrides, Windows::UI::Xaml::IUIElementOverrides7, Windows::UI::Xaml::IUIElementOverrides8, Windows::UI::Xaml::IUIElementOverrides9>
{
    ColorPicker(std::nullptr_t) noexcept {}
    ColorPicker();
    static Windows::UI::Xaml::DependencyProperty ColorProperty();
    static Windows::UI::Xaml::DependencyProperty PreviousColorProperty();
    static Windows::UI::Xaml::DependencyProperty IsAlphaEnabledProperty();
    static Windows::UI::Xaml::DependencyProperty IsColorSpectrumVisibleProperty();
    static Windows::UI::Xaml::DependencyProperty IsColorPreviewVisibleProperty();
    static Windows::UI::Xaml::DependencyProperty IsColorSliderVisibleProperty();
    static Windows::UI::Xaml::DependencyProperty IsAlphaSliderVisibleProperty();
    static Windows::UI::Xaml::DependencyProperty IsMoreButtonVisibleProperty();
    static Windows::UI::Xaml::DependencyProperty IsColorChannelTextInputVisibleProperty();
    static Windows::UI::Xaml::DependencyProperty IsAlphaTextInputVisibleProperty();
    static Windows::UI::Xaml::DependencyProperty IsHexInputVisibleProperty();
    static Windows::UI::Xaml::DependencyProperty MinHueProperty();
    static Windows::UI::Xaml::DependencyProperty MaxHueProperty();
    static Windows::UI::Xaml::DependencyProperty MinSaturationProperty();
    static Windows::UI::Xaml::DependencyProperty MaxSaturationProperty();
    static Windows::UI::Xaml::DependencyProperty MinValueProperty();
    static Windows::UI::Xaml::DependencyProperty MaxValueProperty();
    static Windows::UI::Xaml::DependencyProperty ColorSpectrumShapeProperty();
    static Windows::UI::Xaml::DependencyProperty ColorSpectrumComponentsProperty();
};

struct WINRT_EBO CommandBarFlyout :
    Microsoft::UI::Xaml::Controls::ICommandBarFlyout,
    impl::base<CommandBarFlyout, Windows::UI::Xaml::Controls::Primitives::FlyoutBase, Windows::UI::Xaml::DependencyObject>,
    impl::require<CommandBarFlyout, Windows::UI::Xaml::Controls::Primitives::IFlyoutBase, Windows::UI::Xaml::Controls::Primitives::IFlyoutBase2, Windows::UI::Xaml::Controls::Primitives::IFlyoutBase3, Windows::UI::Xaml::Controls::Primitives::IFlyoutBase4, Windows::UI::Xaml::Controls::Primitives::IFlyoutBase5, Windows::UI::Xaml::Controls::Primitives::IFlyoutBaseOverrides, Windows::UI::Xaml::Controls::Primitives::IFlyoutBaseOverrides4, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2>
{
    CommandBarFlyout(std::nullptr_t) noexcept {}
    CommandBarFlyout();
    using impl::consume_t<CommandBarFlyout, Windows::UI::Xaml::Controls::Primitives::IFlyoutBase>::ShowAt;
    using impl::consume_t<CommandBarFlyout, Windows::UI::Xaml::Controls::Primitives::IFlyoutBase5>::ShowAt;
};

struct WINRT_EBO DropDownButton :
    Microsoft::UI::Xaml::Controls::IDropDownButton,
    impl::base<DropDownButton, Windows::UI::Xaml::Controls::Button, Windows::UI::Xaml::Controls::Primitives::ButtonBase, Windows::UI::Xaml::Controls::ContentControl, Windows::UI::Xaml::Controls::Control, Windows::UI::Xaml::FrameworkElement, Windows::UI::Xaml::UIElement, Windows::UI::Xaml::DependencyObject>,
    impl::require<DropDownButton, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::Controls::IButton, Windows::UI::Xaml::Controls::IButtonWithFlyout, Windows::UI::Xaml::Controls::IContentControl, Windows::UI::Xaml::Controls::IContentControl2, Windows::UI::Xaml::Controls::IContentControlOverrides, Windows::UI::Xaml::Controls::IControl, Windows::UI::Xaml::Controls::IControl2, Windows::UI::Xaml::Controls::IControl3, Windows::UI::Xaml::Controls::IControl4, Windows::UI::Xaml::Controls::IControl5, Windows::UI::Xaml::Controls::IControl7, Windows::UI::Xaml::Controls::IControlOverrides, Windows::UI::Xaml::Controls::IControlOverrides6, Windows::UI::Xaml::Controls::IControlProtected, Windows::UI::Xaml::Controls::Primitives::IButtonBase, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::IFrameworkElement, Windows::UI::Xaml::IFrameworkElement2, Windows::UI::Xaml::IFrameworkElement3, Windows::UI::Xaml::IFrameworkElement4, Windows::UI::Xaml::IFrameworkElement6, Windows::UI::Xaml::IFrameworkElement7, Windows::UI::Xaml::IFrameworkElementOverrides, Windows::UI::Xaml::IFrameworkElementOverrides2, Windows::UI::Xaml::IFrameworkElementProtected7, Windows::UI::Xaml::IUIElement, Windows::UI::Xaml::IUIElement2, Windows::UI::Xaml::IUIElement3, Windows::UI::Xaml::IUIElement4, Windows::UI::Xaml::IUIElement5, Windows::UI::Xaml::IUIElement7, Windows::UI::Xaml::IUIElement8, Windows::UI::Xaml::IUIElement9, Windows::UI::Xaml::IUIElementOverrides, Windows::UI::Xaml::IUIElementOverrides7, Windows::UI::Xaml::IUIElementOverrides8, Windows::UI::Xaml::IUIElementOverrides9>
{
    DropDownButton(std::nullptr_t) noexcept {}
    DropDownButton();
};

struct WINRT_EBO DropDownButtonAutomationPeer :
    Microsoft::UI::Xaml::Controls::IDropDownButtonAutomationPeer,
    impl::base<DropDownButtonAutomationPeer, Windows::UI::Xaml::Automation::Peers::ButtonAutomationPeer, Windows::UI::Xaml::Automation::Peers::ButtonBaseAutomationPeer, Windows::UI::Xaml::Automation::Peers::FrameworkElementAutomationPeer, Windows::UI::Xaml::Automation::Peers::AutomationPeer, Windows::UI::Xaml::DependencyObject>,
    impl::require<DropDownButtonAutomationPeer, Windows::UI::Xaml::Automation::Peers::IAutomationPeer, Windows::UI::Xaml::Automation::Peers::IAutomationPeer2, Windows::UI::Xaml::Automation::Peers::IAutomationPeer3, Windows::UI::Xaml::Automation::Peers::IAutomationPeer4, Windows::UI::Xaml::Automation::Peers::IAutomationPeer5, Windows::UI::Xaml::Automation::Peers::IAutomationPeer6, Windows::UI::Xaml::Automation::Peers::IAutomationPeer7, Windows::UI::Xaml::Automation::Peers::IAutomationPeer8, Windows::UI::Xaml::Automation::Peers::IAutomationPeer9, Windows::UI::Xaml::Automation::Peers::IAutomationPeerOverrides, Windows::UI::Xaml::Automation::Peers::IAutomationPeerOverrides2, Windows::UI::Xaml::Automation::Peers::IAutomationPeerOverrides3, Windows::UI::Xaml::Automation::Peers::IAutomationPeerOverrides4, Windows::UI::Xaml::Automation::Peers::IAutomationPeerOverrides5, Windows::UI::Xaml::Automation::Peers::IAutomationPeerOverrides6, Windows::UI::Xaml::Automation::Peers::IAutomationPeerOverrides8, Windows::UI::Xaml::Automation::Peers::IAutomationPeerOverrides9, Windows::UI::Xaml::Automation::Peers::IAutomationPeerProtected, Windows::UI::Xaml::Automation::Peers::IButtonAutomationPeer, Windows::UI::Xaml::Automation::Peers::IButtonBaseAutomationPeer, Windows::UI::Xaml::Automation::Peers::IFrameworkElementAutomationPeer, Windows::UI::Xaml::Automation::Provider::IExpandCollapseProvider, Windows::UI::Xaml::Automation::Provider::IInvokeProvider, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2>
{
    DropDownButtonAutomationPeer(std::nullptr_t) noexcept {}
    DropDownButtonAutomationPeer(Microsoft::UI::Xaml::Controls::DropDownButton const& owner);
};

struct WINRT_EBO FontIconSource :
    Microsoft::UI::Xaml::Controls::IFontIconSource,
    impl::base<FontIconSource, Microsoft::UI::Xaml::Controls::IconSource, Windows::UI::Xaml::DependencyObject>,
    impl::require<FontIconSource, Microsoft::UI::Xaml::Controls::IIconSource, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2>
{
    FontIconSource(std::nullptr_t) noexcept {}
    FontIconSource();
    static Windows::UI::Xaml::DependencyProperty GlyphProperty();
    static Windows::UI::Xaml::DependencyProperty FontSizeProperty();
    static Windows::UI::Xaml::DependencyProperty FontFamilyProperty();
    static Windows::UI::Xaml::DependencyProperty FontWeightProperty();
    static Windows::UI::Xaml::DependencyProperty FontStyleProperty();
    static Windows::UI::Xaml::DependencyProperty IsTextScaleFactorEnabledProperty();
    static Windows::UI::Xaml::DependencyProperty MirroredWhenRightToLeftProperty();
};

struct WINRT_EBO IconSource :
    Microsoft::UI::Xaml::Controls::IIconSource,
    impl::base<IconSource, Windows::UI::Xaml::DependencyObject>,
    impl::require<IconSource, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2>
{
    IconSource(std::nullptr_t) noexcept {}
    static Windows::UI::Xaml::DependencyProperty ForegroundProperty();
};

struct WINRT_EBO MenuBar :
    Microsoft::UI::Xaml::Controls::IMenuBar,
    impl::base<MenuBar, Windows::UI::Xaml::Controls::Control, Windows::UI::Xaml::FrameworkElement, Windows::UI::Xaml::UIElement, Windows::UI::Xaml::DependencyObject>,
    impl::require<MenuBar, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::Controls::IControl, Windows::UI::Xaml::Controls::IControl2, Windows::UI::Xaml::Controls::IControl3, Windows::UI::Xaml::Controls::IControl4, Windows::UI::Xaml::Controls::IControl5, Windows::UI::Xaml::Controls::IControl7, Windows::UI::Xaml::Controls::IControlOverrides, Windows::UI::Xaml::Controls::IControlOverrides6, Windows::UI::Xaml::Controls::IControlProtected, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::IFrameworkElement, Windows::UI::Xaml::IFrameworkElement2, Windows::UI::Xaml::IFrameworkElement3, Windows::UI::Xaml::IFrameworkElement4, Windows::UI::Xaml::IFrameworkElement6, Windows::UI::Xaml::IFrameworkElement7, Windows::UI::Xaml::IFrameworkElementOverrides, Windows::UI::Xaml::IFrameworkElementOverrides2, Windows::UI::Xaml::IFrameworkElementProtected7, Windows::UI::Xaml::IUIElement, Windows::UI::Xaml::IUIElement2, Windows::UI::Xaml::IUIElement3, Windows::UI::Xaml::IUIElement4, Windows::UI::Xaml::IUIElement5, Windows::UI::Xaml::IUIElement7, Windows::UI::Xaml::IUIElement8, Windows::UI::Xaml::IUIElement9, Windows::UI::Xaml::IUIElementOverrides, Windows::UI::Xaml::IUIElementOverrides7, Windows::UI::Xaml::IUIElementOverrides8, Windows::UI::Xaml::IUIElementOverrides9>
{
    MenuBar(std::nullptr_t) noexcept {}
    MenuBar();
    static Windows::UI::Xaml::DependencyProperty ItemsProperty();
};

struct WINRT_EBO MenuBarItem :
    Microsoft::UI::Xaml::Controls::IMenuBarItem,
    impl::base<MenuBarItem, Windows::UI::Xaml::Controls::Control, Windows::UI::Xaml::FrameworkElement, Windows::UI::Xaml::UIElement, Windows::UI::Xaml::DependencyObject>,
    impl::require<MenuBarItem, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::Controls::IControl, Windows::UI::Xaml::Controls::IControl2, Windows::UI::Xaml::Controls::IControl3, Windows::UI::Xaml::Controls::IControl4, Windows::UI::Xaml::Controls::IControl5, Windows::UI::Xaml::Controls::IControl7, Windows::UI::Xaml::Controls::IControlOverrides, Windows::UI::Xaml::Controls::IControlOverrides6, Windows::UI::Xaml::Controls::IControlProtected, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::IFrameworkElement, Windows::UI::Xaml::IFrameworkElement2, Windows::UI::Xaml::IFrameworkElement3, Windows::UI::Xaml::IFrameworkElement4, Windows::UI::Xaml::IFrameworkElement6, Windows::UI::Xaml::IFrameworkElement7, Windows::UI::Xaml::IFrameworkElementOverrides, Windows::UI::Xaml::IFrameworkElementOverrides2, Windows::UI::Xaml::IFrameworkElementProtected7, Windows::UI::Xaml::IUIElement, Windows::UI::Xaml::IUIElement2, Windows::UI::Xaml::IUIElement3, Windows::UI::Xaml::IUIElement4, Windows::UI::Xaml::IUIElement5, Windows::UI::Xaml::IUIElement7, Windows::UI::Xaml::IUIElement8, Windows::UI::Xaml::IUIElement9, Windows::UI::Xaml::IUIElementOverrides, Windows::UI::Xaml::IUIElementOverrides7, Windows::UI::Xaml::IUIElementOverrides8, Windows::UI::Xaml::IUIElementOverrides9>
{
    MenuBarItem(std::nullptr_t) noexcept {}
    MenuBarItem();
    static Windows::UI::Xaml::DependencyProperty TitleProperty();
    static Windows::UI::Xaml::DependencyProperty ItemsProperty();
};

struct WINRT_EBO MenuBarItemFlyout :
    Microsoft::UI::Xaml::Controls::IMenuBarItemFlyout,
    impl::base<MenuBarItemFlyout, Windows::UI::Xaml::Controls::MenuFlyout, Windows::UI::Xaml::Controls::Primitives::FlyoutBase, Windows::UI::Xaml::DependencyObject>,
    impl::require<MenuBarItemFlyout, Windows::UI::Xaml::Controls::IMenuFlyout, Windows::UI::Xaml::Controls::IMenuFlyout2, Windows::UI::Xaml::Controls::Primitives::IFlyoutBase, Windows::UI::Xaml::Controls::Primitives::IFlyoutBase2, Windows::UI::Xaml::Controls::Primitives::IFlyoutBase3, Windows::UI::Xaml::Controls::Primitives::IFlyoutBase4, Windows::UI::Xaml::Controls::Primitives::IFlyoutBase5, Windows::UI::Xaml::Controls::Primitives::IFlyoutBaseOverrides, Windows::UI::Xaml::Controls::Primitives::IFlyoutBaseOverrides4, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2>
{
    MenuBarItemFlyout(std::nullptr_t) noexcept {}
    MenuBarItemFlyout();
    using impl::consume_t<MenuBarItemFlyout, Windows::UI::Xaml::Controls::IMenuFlyout2>::ShowAt;
    using impl::consume_t<MenuBarItemFlyout, Windows::UI::Xaml::Controls::Primitives::IFlyoutBase>::ShowAt;
    using impl::consume_t<MenuBarItemFlyout, Windows::UI::Xaml::Controls::Primitives::IFlyoutBase5>::ShowAt;
};

struct WINRT_EBO NavigationView :
    Microsoft::UI::Xaml::Controls::INavigationView,
    impl::base<NavigationView, Windows::UI::Xaml::Controls::ContentControl, Windows::UI::Xaml::Controls::Control, Windows::UI::Xaml::FrameworkElement, Windows::UI::Xaml::UIElement, Windows::UI::Xaml::DependencyObject>,
    impl::require<NavigationView, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::Controls::IContentControl, Windows::UI::Xaml::Controls::IContentControl2, Windows::UI::Xaml::Controls::IContentControlOverrides, Windows::UI::Xaml::Controls::IControl, Windows::UI::Xaml::Controls::IControl2, Windows::UI::Xaml::Controls::IControl3, Windows::UI::Xaml::Controls::IControl4, Windows::UI::Xaml::Controls::IControl5, Windows::UI::Xaml::Controls::IControl7, Windows::UI::Xaml::Controls::IControlOverrides, Windows::UI::Xaml::Controls::IControlOverrides6, Windows::UI::Xaml::Controls::IControlProtected, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::IFrameworkElement, Windows::UI::Xaml::IFrameworkElement2, Windows::UI::Xaml::IFrameworkElement3, Windows::UI::Xaml::IFrameworkElement4, Windows::UI::Xaml::IFrameworkElement6, Windows::UI::Xaml::IFrameworkElement7, Windows::UI::Xaml::IFrameworkElementOverrides, Windows::UI::Xaml::IFrameworkElementOverrides2, Windows::UI::Xaml::IFrameworkElementProtected7, Windows::UI::Xaml::IUIElement, Windows::UI::Xaml::IUIElement2, Windows::UI::Xaml::IUIElement3, Windows::UI::Xaml::IUIElement4, Windows::UI::Xaml::IUIElement5, Windows::UI::Xaml::IUIElement7, Windows::UI::Xaml::IUIElement8, Windows::UI::Xaml::IUIElement9, Windows::UI::Xaml::IUIElementOverrides, Windows::UI::Xaml::IUIElementOverrides7, Windows::UI::Xaml::IUIElementOverrides8, Windows::UI::Xaml::IUIElementOverrides9>
{
    NavigationView(std::nullptr_t) noexcept {}
    NavigationView();
    static Windows::UI::Xaml::DependencyProperty IsPaneOpenProperty();
    static Windows::UI::Xaml::DependencyProperty CompactModeThresholdWidthProperty();
    static Windows::UI::Xaml::DependencyProperty ExpandedModeThresholdWidthProperty();
    static Windows::UI::Xaml::DependencyProperty PaneFooterProperty();
    static Windows::UI::Xaml::DependencyProperty HeaderProperty();
    static Windows::UI::Xaml::DependencyProperty HeaderTemplateProperty();
    static Windows::UI::Xaml::DependencyProperty DisplayModeProperty();
    static Windows::UI::Xaml::DependencyProperty IsSettingsVisibleProperty();
    static Windows::UI::Xaml::DependencyProperty IsPaneToggleButtonVisibleProperty();
    static Windows::UI::Xaml::DependencyProperty AlwaysShowHeaderProperty();
    static Windows::UI::Xaml::DependencyProperty CompactPaneLengthProperty();
    static Windows::UI::Xaml::DependencyProperty OpenPaneLengthProperty();
    static Windows::UI::Xaml::DependencyProperty PaneToggleButtonStyleProperty();
    static Windows::UI::Xaml::DependencyProperty MenuItemsProperty();
    static Windows::UI::Xaml::DependencyProperty MenuItemsSourceProperty();
    static Windows::UI::Xaml::DependencyProperty SelectedItemProperty();
    static Windows::UI::Xaml::DependencyProperty SettingsItemProperty();
    static Windows::UI::Xaml::DependencyProperty AutoSuggestBoxProperty();
    static Windows::UI::Xaml::DependencyProperty MenuItemTemplateProperty();
    static Windows::UI::Xaml::DependencyProperty MenuItemTemplateSelectorProperty();
    static Windows::UI::Xaml::DependencyProperty MenuItemContainerStyleProperty();
    static Windows::UI::Xaml::DependencyProperty MenuItemContainerStyleSelectorProperty();
    static Windows::UI::Xaml::DependencyProperty IsBackButtonVisibleProperty();
    static Windows::UI::Xaml::DependencyProperty IsBackEnabledProperty();
    static Windows::UI::Xaml::DependencyProperty PaneTitleProperty();
    static Windows::UI::Xaml::DependencyProperty PaneDisplayModeProperty();
    static Windows::UI::Xaml::DependencyProperty PaneHeaderProperty();
    static Windows::UI::Xaml::DependencyProperty PaneCustomContentProperty();
    static Windows::UI::Xaml::DependencyProperty ContentOverlayProperty();
    static Windows::UI::Xaml::DependencyProperty IsPaneVisibleProperty();
    static Windows::UI::Xaml::DependencyProperty SelectionFollowsFocusProperty();
    static Windows::UI::Xaml::DependencyProperty TemplateSettingsProperty();
    static Windows::UI::Xaml::DependencyProperty ShoulderNavigationEnabledProperty();
    static Windows::UI::Xaml::DependencyProperty OverflowLabelModeProperty();
};

struct WINRT_EBO NavigationViewBackRequestedEventArgs :
    Microsoft::UI::Xaml::Controls::INavigationViewBackRequestedEventArgs
{
    NavigationViewBackRequestedEventArgs(std::nullptr_t) noexcept {}
};

struct WINRT_EBO NavigationViewDisplayModeChangedEventArgs :
    Microsoft::UI::Xaml::Controls::INavigationViewDisplayModeChangedEventArgs
{
    NavigationViewDisplayModeChangedEventArgs(std::nullptr_t) noexcept {}
};

struct WINRT_EBO NavigationViewItem :
    Microsoft::UI::Xaml::Controls::INavigationViewItem,
    impl::base<NavigationViewItem, Microsoft::UI::Xaml::Controls::NavigationViewItemBase, Windows::UI::Xaml::Controls::ListViewItem, Windows::UI::Xaml::Controls::Primitives::SelectorItem, Windows::UI::Xaml::Controls::ContentControl, Windows::UI::Xaml::Controls::Control, Windows::UI::Xaml::FrameworkElement, Windows::UI::Xaml::UIElement, Windows::UI::Xaml::DependencyObject>,
    impl::require<NavigationViewItem, Microsoft::UI::Xaml::Controls::INavigationViewItemBase, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::Controls::IContentControl, Windows::UI::Xaml::Controls::IContentControl2, Windows::UI::Xaml::Controls::IContentControlOverrides, Windows::UI::Xaml::Controls::IControl, Windows::UI::Xaml::Controls::IControl2, Windows::UI::Xaml::Controls::IControl3, Windows::UI::Xaml::Controls::IControl4, Windows::UI::Xaml::Controls::IControl5, Windows::UI::Xaml::Controls::IControl7, Windows::UI::Xaml::Controls::IControlOverrides, Windows::UI::Xaml::Controls::IControlOverrides6, Windows::UI::Xaml::Controls::IControlProtected, Windows::UI::Xaml::Controls::IListViewItem, Windows::UI::Xaml::Controls::Primitives::ISelectorItem, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::IFrameworkElement, Windows::UI::Xaml::IFrameworkElement2, Windows::UI::Xaml::IFrameworkElement3, Windows::UI::Xaml::IFrameworkElement4, Windows::UI::Xaml::IFrameworkElement6, Windows::UI::Xaml::IFrameworkElement7, Windows::UI::Xaml::IFrameworkElementOverrides, Windows::UI::Xaml::IFrameworkElementOverrides2, Windows::UI::Xaml::IFrameworkElementProtected7, Windows::UI::Xaml::IUIElement, Windows::UI::Xaml::IUIElement2, Windows::UI::Xaml::IUIElement3, Windows::UI::Xaml::IUIElement4, Windows::UI::Xaml::IUIElement5, Windows::UI::Xaml::IUIElement7, Windows::UI::Xaml::IUIElement8, Windows::UI::Xaml::IUIElement9, Windows::UI::Xaml::IUIElementOverrides, Windows::UI::Xaml::IUIElementOverrides7, Windows::UI::Xaml::IUIElementOverrides8, Windows::UI::Xaml::IUIElementOverrides9>
{
    NavigationViewItem(std::nullptr_t) noexcept {}
    NavigationViewItem();
    static Windows::UI::Xaml::DependencyProperty IconProperty();
    static Windows::UI::Xaml::DependencyProperty CompactPaneLengthProperty();
    static Windows::UI::Xaml::DependencyProperty SelectsOnInvokedProperty();
};

struct WINRT_EBO NavigationViewItemBase :
    Microsoft::UI::Xaml::Controls::INavigationViewItemBase,
    impl::base<NavigationViewItemBase, Windows::UI::Xaml::Controls::ListViewItem, Windows::UI::Xaml::Controls::Primitives::SelectorItem, Windows::UI::Xaml::Controls::ContentControl, Windows::UI::Xaml::Controls::Control, Windows::UI::Xaml::FrameworkElement, Windows::UI::Xaml::UIElement, Windows::UI::Xaml::DependencyObject>,
    impl::require<NavigationViewItemBase, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::Controls::IContentControl, Windows::UI::Xaml::Controls::IContentControl2, Windows::UI::Xaml::Controls::IContentControlOverrides, Windows::UI::Xaml::Controls::IControl, Windows::UI::Xaml::Controls::IControl2, Windows::UI::Xaml::Controls::IControl3, Windows::UI::Xaml::Controls::IControl4, Windows::UI::Xaml::Controls::IControl5, Windows::UI::Xaml::Controls::IControl7, Windows::UI::Xaml::Controls::IControlOverrides, Windows::UI::Xaml::Controls::IControlOverrides6, Windows::UI::Xaml::Controls::IControlProtected, Windows::UI::Xaml::Controls::IListViewItem, Windows::UI::Xaml::Controls::Primitives::ISelectorItem, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::IFrameworkElement, Windows::UI::Xaml::IFrameworkElement2, Windows::UI::Xaml::IFrameworkElement3, Windows::UI::Xaml::IFrameworkElement4, Windows::UI::Xaml::IFrameworkElement6, Windows::UI::Xaml::IFrameworkElement7, Windows::UI::Xaml::IFrameworkElementOverrides, Windows::UI::Xaml::IFrameworkElementOverrides2, Windows::UI::Xaml::IFrameworkElementProtected7, Windows::UI::Xaml::IUIElement, Windows::UI::Xaml::IUIElement2, Windows::UI::Xaml::IUIElement3, Windows::UI::Xaml::IUIElement4, Windows::UI::Xaml::IUIElement5, Windows::UI::Xaml::IUIElement7, Windows::UI::Xaml::IUIElement8, Windows::UI::Xaml::IUIElement9, Windows::UI::Xaml::IUIElementOverrides, Windows::UI::Xaml::IUIElementOverrides7, Windows::UI::Xaml::IUIElementOverrides8, Windows::UI::Xaml::IUIElementOverrides9>
{
    NavigationViewItemBase(std::nullptr_t) noexcept {}
};

struct WINRT_EBO NavigationViewItemHeader :
    Microsoft::UI::Xaml::Controls::INavigationViewItemHeader,
    impl::base<NavigationViewItemHeader, Microsoft::UI::Xaml::Controls::NavigationViewItemBase, Windows::UI::Xaml::Controls::ListViewItem, Windows::UI::Xaml::Controls::Primitives::SelectorItem, Windows::UI::Xaml::Controls::ContentControl, Windows::UI::Xaml::Controls::Control, Windows::UI::Xaml::FrameworkElement, Windows::UI::Xaml::UIElement, Windows::UI::Xaml::DependencyObject>,
    impl::require<NavigationViewItemHeader, Microsoft::UI::Xaml::Controls::INavigationViewItemBase, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::Controls::IContentControl, Windows::UI::Xaml::Controls::IContentControl2, Windows::UI::Xaml::Controls::IContentControlOverrides, Windows::UI::Xaml::Controls::IControl, Windows::UI::Xaml::Controls::IControl2, Windows::UI::Xaml::Controls::IControl3, Windows::UI::Xaml::Controls::IControl4, Windows::UI::Xaml::Controls::IControl5, Windows::UI::Xaml::Controls::IControl7, Windows::UI::Xaml::Controls::IControlOverrides, Windows::UI::Xaml::Controls::IControlOverrides6, Windows::UI::Xaml::Controls::IControlProtected, Windows::UI::Xaml::Controls::IListViewItem, Windows::UI::Xaml::Controls::Primitives::ISelectorItem, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::IFrameworkElement, Windows::UI::Xaml::IFrameworkElement2, Windows::UI::Xaml::IFrameworkElement3, Windows::UI::Xaml::IFrameworkElement4, Windows::UI::Xaml::IFrameworkElement6, Windows::UI::Xaml::IFrameworkElement7, Windows::UI::Xaml::IFrameworkElementOverrides, Windows::UI::Xaml::IFrameworkElementOverrides2, Windows::UI::Xaml::IFrameworkElementProtected7, Windows::UI::Xaml::IUIElement, Windows::UI::Xaml::IUIElement2, Windows::UI::Xaml::IUIElement3, Windows::UI::Xaml::IUIElement4, Windows::UI::Xaml::IUIElement5, Windows::UI::Xaml::IUIElement7, Windows::UI::Xaml::IUIElement8, Windows::UI::Xaml::IUIElement9, Windows::UI::Xaml::IUIElementOverrides, Windows::UI::Xaml::IUIElementOverrides7, Windows::UI::Xaml::IUIElementOverrides8, Windows::UI::Xaml::IUIElementOverrides9>
{
    NavigationViewItemHeader(std::nullptr_t) noexcept {}
    NavigationViewItemHeader();
};

struct WINRT_EBO NavigationViewItemInvokedEventArgs :
    Microsoft::UI::Xaml::Controls::INavigationViewItemInvokedEventArgs
{
    NavigationViewItemInvokedEventArgs(std::nullptr_t) noexcept {}
    NavigationViewItemInvokedEventArgs();
};

struct WINRT_EBO NavigationViewItemSeparator :
    Microsoft::UI::Xaml::Controls::INavigationViewItemSeparator,
    impl::base<NavigationViewItemSeparator, Microsoft::UI::Xaml::Controls::NavigationViewItemBase, Windows::UI::Xaml::Controls::ListViewItem, Windows::UI::Xaml::Controls::Primitives::SelectorItem, Windows::UI::Xaml::Controls::ContentControl, Windows::UI::Xaml::Controls::Control, Windows::UI::Xaml::FrameworkElement, Windows::UI::Xaml::UIElement, Windows::UI::Xaml::DependencyObject>,
    impl::require<NavigationViewItemSeparator, Microsoft::UI::Xaml::Controls::INavigationViewItemBase, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::Controls::IContentControl, Windows::UI::Xaml::Controls::IContentControl2, Windows::UI::Xaml::Controls::IContentControlOverrides, Windows::UI::Xaml::Controls::IControl, Windows::UI::Xaml::Controls::IControl2, Windows::UI::Xaml::Controls::IControl3, Windows::UI::Xaml::Controls::IControl4, Windows::UI::Xaml::Controls::IControl5, Windows::UI::Xaml::Controls::IControl7, Windows::UI::Xaml::Controls::IControlOverrides, Windows::UI::Xaml::Controls::IControlOverrides6, Windows::UI::Xaml::Controls::IControlProtected, Windows::UI::Xaml::Controls::IListViewItem, Windows::UI::Xaml::Controls::Primitives::ISelectorItem, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::IFrameworkElement, Windows::UI::Xaml::IFrameworkElement2, Windows::UI::Xaml::IFrameworkElement3, Windows::UI::Xaml::IFrameworkElement4, Windows::UI::Xaml::IFrameworkElement6, Windows::UI::Xaml::IFrameworkElement7, Windows::UI::Xaml::IFrameworkElementOverrides, Windows::UI::Xaml::IFrameworkElementOverrides2, Windows::UI::Xaml::IFrameworkElementProtected7, Windows::UI::Xaml::IUIElement, Windows::UI::Xaml::IUIElement2, Windows::UI::Xaml::IUIElement3, Windows::UI::Xaml::IUIElement4, Windows::UI::Xaml::IUIElement5, Windows::UI::Xaml::IUIElement7, Windows::UI::Xaml::IUIElement8, Windows::UI::Xaml::IUIElement9, Windows::UI::Xaml::IUIElementOverrides, Windows::UI::Xaml::IUIElementOverrides7, Windows::UI::Xaml::IUIElementOverrides8, Windows::UI::Xaml::IUIElementOverrides9>
{
    NavigationViewItemSeparator(std::nullptr_t) noexcept {}
    NavigationViewItemSeparator();
};

struct WINRT_EBO NavigationViewList :
    Microsoft::UI::Xaml::Controls::INavigationViewList,
    impl::base<NavigationViewList, Windows::UI::Xaml::Controls::ListView, Windows::UI::Xaml::Controls::ListViewBase, Windows::UI::Xaml::Controls::Primitives::Selector, Windows::UI::Xaml::Controls::ItemsControl, Windows::UI::Xaml::Controls::Control, Windows::UI::Xaml::FrameworkElement, Windows::UI::Xaml::UIElement, Windows::UI::Xaml::DependencyObject>,
    impl::require<NavigationViewList, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::Controls::IControl, Windows::UI::Xaml::Controls::IControl2, Windows::UI::Xaml::Controls::IControl3, Windows::UI::Xaml::Controls::IControl4, Windows::UI::Xaml::Controls::IControl5, Windows::UI::Xaml::Controls::IControl7, Windows::UI::Xaml::Controls::IControlOverrides, Windows::UI::Xaml::Controls::IControlOverrides6, Windows::UI::Xaml::Controls::IControlProtected, Windows::UI::Xaml::Controls::IItemContainerMapping, Windows::UI::Xaml::Controls::IItemsControl, Windows::UI::Xaml::Controls::IItemsControl2, Windows::UI::Xaml::Controls::IItemsControl3, Windows::UI::Xaml::Controls::IItemsControlOverrides, Windows::UI::Xaml::Controls::IListView, Windows::UI::Xaml::Controls::IListViewBase, Windows::UI::Xaml::Controls::IListViewBase2, Windows::UI::Xaml::Controls::IListViewBase3, Windows::UI::Xaml::Controls::IListViewBase4, Windows::UI::Xaml::Controls::IListViewBase5, Windows::UI::Xaml::Controls::IListViewBase6, Windows::UI::Xaml::Controls::ISemanticZoomInformation, Windows::UI::Xaml::Controls::Primitives::ISelector, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::IFrameworkElement, Windows::UI::Xaml::IFrameworkElement2, Windows::UI::Xaml::IFrameworkElement3, Windows::UI::Xaml::IFrameworkElement4, Windows::UI::Xaml::IFrameworkElement6, Windows::UI::Xaml::IFrameworkElement7, Windows::UI::Xaml::IFrameworkElementOverrides, Windows::UI::Xaml::IFrameworkElementOverrides2, Windows::UI::Xaml::IFrameworkElementProtected7, Windows::UI::Xaml::IUIElement, Windows::UI::Xaml::IUIElement2, Windows::UI::Xaml::IUIElement3, Windows::UI::Xaml::IUIElement4, Windows::UI::Xaml::IUIElement5, Windows::UI::Xaml::IUIElement7, Windows::UI::Xaml::IUIElement8, Windows::UI::Xaml::IUIElement9, Windows::UI::Xaml::IUIElementOverrides, Windows::UI::Xaml::IUIElementOverrides7, Windows::UI::Xaml::IUIElementOverrides8, Windows::UI::Xaml::IUIElementOverrides9>
{
    NavigationViewList(std::nullptr_t) noexcept {}
    NavigationViewList();
};

struct WINRT_EBO NavigationViewPaneClosingEventArgs :
    Microsoft::UI::Xaml::Controls::INavigationViewPaneClosingEventArgs
{
    NavigationViewPaneClosingEventArgs(std::nullptr_t) noexcept {}
};

struct WINRT_EBO NavigationViewSelectionChangedEventArgs :
    Microsoft::UI::Xaml::Controls::INavigationViewSelectionChangedEventArgs
{
    NavigationViewSelectionChangedEventArgs(std::nullptr_t) noexcept {}
};

struct WINRT_EBO NavigationViewTemplateSettings :
    Microsoft::UI::Xaml::Controls::INavigationViewTemplateSettings,
    impl::base<NavigationViewTemplateSettings, Windows::UI::Xaml::DependencyObject>,
    impl::require<NavigationViewTemplateSettings, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2>
{
    NavigationViewTemplateSettings(std::nullptr_t) noexcept {}
    NavigationViewTemplateSettings();
    static Windows::UI::Xaml::DependencyProperty TopPaddingProperty();
    static Windows::UI::Xaml::DependencyProperty OverflowButtonVisibilityProperty();
    static Windows::UI::Xaml::DependencyProperty PaneToggleButtonVisibilityProperty();
    static Windows::UI::Xaml::DependencyProperty BackButtonVisibilityProperty();
    static Windows::UI::Xaml::DependencyProperty TopPaneVisibilityProperty();
    static Windows::UI::Xaml::DependencyProperty LeftPaneVisibilityProperty();
    static Windows::UI::Xaml::DependencyProperty SingleSelectionFollowsFocusProperty();
};

struct WINRT_EBO ParallaxView :
    Microsoft::UI::Xaml::Controls::IParallaxView,
    impl::base<ParallaxView, Windows::UI::Xaml::FrameworkElement, Windows::UI::Xaml::UIElement, Windows::UI::Xaml::DependencyObject>,
    impl::require<ParallaxView, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::IFrameworkElement, Windows::UI::Xaml::IFrameworkElement2, Windows::UI::Xaml::IFrameworkElement3, Windows::UI::Xaml::IFrameworkElement4, Windows::UI::Xaml::IFrameworkElement6, Windows::UI::Xaml::IFrameworkElement7, Windows::UI::Xaml::IFrameworkElementOverrides, Windows::UI::Xaml::IFrameworkElementOverrides2, Windows::UI::Xaml::IFrameworkElementProtected7, Windows::UI::Xaml::IUIElement, Windows::UI::Xaml::IUIElement2, Windows::UI::Xaml::IUIElement3, Windows::UI::Xaml::IUIElement4, Windows::UI::Xaml::IUIElement5, Windows::UI::Xaml::IUIElement7, Windows::UI::Xaml::IUIElement8, Windows::UI::Xaml::IUIElement9, Windows::UI::Xaml::IUIElementOverrides, Windows::UI::Xaml::IUIElementOverrides7, Windows::UI::Xaml::IUIElementOverrides8, Windows::UI::Xaml::IUIElementOverrides9>
{
    ParallaxView(std::nullptr_t) noexcept {}
    ParallaxView();
    static Windows::UI::Xaml::DependencyProperty ChildProperty();
    static Windows::UI::Xaml::DependencyProperty HorizontalSourceEndOffsetProperty();
    static Windows::UI::Xaml::DependencyProperty HorizontalSourceOffsetKindProperty();
    static Windows::UI::Xaml::DependencyProperty HorizontalSourceStartOffsetProperty();
    static Windows::UI::Xaml::DependencyProperty MaxHorizontalShiftRatioProperty();
    static Windows::UI::Xaml::DependencyProperty HorizontalShiftProperty();
    static Windows::UI::Xaml::DependencyProperty IsHorizontalShiftClampedProperty();
    static Windows::UI::Xaml::DependencyProperty IsVerticalShiftClampedProperty();
    static Windows::UI::Xaml::DependencyProperty SourceProperty();
    static Windows::UI::Xaml::DependencyProperty VerticalSourceEndOffsetProperty();
    static Windows::UI::Xaml::DependencyProperty VerticalSourceOffsetKindProperty();
    static Windows::UI::Xaml::DependencyProperty VerticalSourceStartOffsetProperty();
    static Windows::UI::Xaml::DependencyProperty MaxVerticalShiftRatioProperty();
    static Windows::UI::Xaml::DependencyProperty VerticalShiftProperty();
};

struct WINRT_EBO PathIconSource :
    Microsoft::UI::Xaml::Controls::IPathIconSource,
    impl::base<PathIconSource, Microsoft::UI::Xaml::Controls::IconSource, Windows::UI::Xaml::DependencyObject>,
    impl::require<PathIconSource, Microsoft::UI::Xaml::Controls::IIconSource, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2>
{
    PathIconSource(std::nullptr_t) noexcept {}
    PathIconSource();
    static Windows::UI::Xaml::DependencyProperty DataProperty();
};

struct WINRT_EBO PersonPicture :
    Microsoft::UI::Xaml::Controls::IPersonPicture,
    impl::base<PersonPicture, Windows::UI::Xaml::Controls::Control, Windows::UI::Xaml::FrameworkElement, Windows::UI::Xaml::UIElement, Windows::UI::Xaml::DependencyObject>,
    impl::require<PersonPicture, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::Controls::IControl, Windows::UI::Xaml::Controls::IControl2, Windows::UI::Xaml::Controls::IControl3, Windows::UI::Xaml::Controls::IControl4, Windows::UI::Xaml::Controls::IControl5, Windows::UI::Xaml::Controls::IControl7, Windows::UI::Xaml::Controls::IControlOverrides, Windows::UI::Xaml::Controls::IControlOverrides6, Windows::UI::Xaml::Controls::IControlProtected, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::IFrameworkElement, Windows::UI::Xaml::IFrameworkElement2, Windows::UI::Xaml::IFrameworkElement3, Windows::UI::Xaml::IFrameworkElement4, Windows::UI::Xaml::IFrameworkElement6, Windows::UI::Xaml::IFrameworkElement7, Windows::UI::Xaml::IFrameworkElementOverrides, Windows::UI::Xaml::IFrameworkElementOverrides2, Windows::UI::Xaml::IFrameworkElementProtected7, Windows::UI::Xaml::IUIElement, Windows::UI::Xaml::IUIElement2, Windows::UI::Xaml::IUIElement3, Windows::UI::Xaml::IUIElement4, Windows::UI::Xaml::IUIElement5, Windows::UI::Xaml::IUIElement7, Windows::UI::Xaml::IUIElement8, Windows::UI::Xaml::IUIElement9, Windows::UI::Xaml::IUIElementOverrides, Windows::UI::Xaml::IUIElementOverrides7, Windows::UI::Xaml::IUIElementOverrides8, Windows::UI::Xaml::IUIElementOverrides9>
{
    PersonPicture(std::nullptr_t) noexcept {}
    PersonPicture();
    static Windows::UI::Xaml::DependencyProperty BadgeNumberProperty();
    static Windows::UI::Xaml::DependencyProperty BadgeGlyphProperty();
    static Windows::UI::Xaml::DependencyProperty BadgeImageSourceProperty();
    static Windows::UI::Xaml::DependencyProperty BadgeTextProperty();
    static Windows::UI::Xaml::DependencyProperty IsGroupProperty();
    static Windows::UI::Xaml::DependencyProperty ContactProperty();
    static Windows::UI::Xaml::DependencyProperty DisplayNameProperty();
    static Windows::UI::Xaml::DependencyProperty InitialsProperty();
    static Windows::UI::Xaml::DependencyProperty PreferSmallImageProperty();
    static Windows::UI::Xaml::DependencyProperty ProfilePictureProperty();
};

struct WINRT_EBO RatingControl :
    Microsoft::UI::Xaml::Controls::IRatingControl,
    impl::base<RatingControl, Windows::UI::Xaml::Controls::Control, Windows::UI::Xaml::FrameworkElement, Windows::UI::Xaml::UIElement, Windows::UI::Xaml::DependencyObject>,
    impl::require<RatingControl, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::Controls::IControl, Windows::UI::Xaml::Controls::IControl2, Windows::UI::Xaml::Controls::IControl3, Windows::UI::Xaml::Controls::IControl4, Windows::UI::Xaml::Controls::IControl5, Windows::UI::Xaml::Controls::IControl7, Windows::UI::Xaml::Controls::IControlOverrides, Windows::UI::Xaml::Controls::IControlOverrides6, Windows::UI::Xaml::Controls::IControlProtected, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::IFrameworkElement, Windows::UI::Xaml::IFrameworkElement2, Windows::UI::Xaml::IFrameworkElement3, Windows::UI::Xaml::IFrameworkElement4, Windows::UI::Xaml::IFrameworkElement6, Windows::UI::Xaml::IFrameworkElement7, Windows::UI::Xaml::IFrameworkElementOverrides, Windows::UI::Xaml::IFrameworkElementOverrides2, Windows::UI::Xaml::IFrameworkElementProtected7, Windows::UI::Xaml::IUIElement, Windows::UI::Xaml::IUIElement2, Windows::UI::Xaml::IUIElement3, Windows::UI::Xaml::IUIElement4, Windows::UI::Xaml::IUIElement5, Windows::UI::Xaml::IUIElement7, Windows::UI::Xaml::IUIElement8, Windows::UI::Xaml::IUIElement9, Windows::UI::Xaml::IUIElementOverrides, Windows::UI::Xaml::IUIElementOverrides7, Windows::UI::Xaml::IUIElementOverrides8, Windows::UI::Xaml::IUIElementOverrides9>
{
    RatingControl(std::nullptr_t) noexcept {}
    RatingControl();
    static Windows::UI::Xaml::DependencyProperty CaptionProperty();
    static Windows::UI::Xaml::DependencyProperty InitialSetValueProperty();
    static Windows::UI::Xaml::DependencyProperty IsClearEnabledProperty();
    static Windows::UI::Xaml::DependencyProperty IsReadOnlyProperty();
    static Windows::UI::Xaml::DependencyProperty MaxRatingProperty();
    static Windows::UI::Xaml::DependencyProperty PlaceholderValueProperty();
    static Windows::UI::Xaml::DependencyProperty ItemInfoProperty();
    static Windows::UI::Xaml::DependencyProperty ValueProperty();
};

struct WINRT_EBO RatingItemFontInfo :
    Microsoft::UI::Xaml::Controls::IRatingItemFontInfo,
    impl::base<RatingItemFontInfo, Microsoft::UI::Xaml::Controls::RatingItemInfo, Windows::UI::Xaml::DependencyObject>,
    impl::require<RatingItemFontInfo, Microsoft::UI::Xaml::Controls::IRatingItemInfo, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2>
{
    RatingItemFontInfo(std::nullptr_t) noexcept {}
    RatingItemFontInfo();
    static Windows::UI::Xaml::DependencyProperty DisabledGlyphProperty();
    static Windows::UI::Xaml::DependencyProperty GlyphProperty();
    static Windows::UI::Xaml::DependencyProperty PlaceholderGlyphProperty();
    static Windows::UI::Xaml::DependencyProperty PointerOverGlyphProperty();
    static Windows::UI::Xaml::DependencyProperty PointerOverPlaceholderGlyphProperty();
    static Windows::UI::Xaml::DependencyProperty UnsetGlyphProperty();
};

struct WINRT_EBO RatingItemImageInfo :
    Microsoft::UI::Xaml::Controls::IRatingItemImageInfo,
    impl::base<RatingItemImageInfo, Microsoft::UI::Xaml::Controls::RatingItemInfo, Windows::UI::Xaml::DependencyObject>,
    impl::require<RatingItemImageInfo, Microsoft::UI::Xaml::Controls::IRatingItemInfo, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2>
{
    RatingItemImageInfo(std::nullptr_t) noexcept {}
    RatingItemImageInfo();
    static Windows::UI::Xaml::DependencyProperty DisabledImageProperty();
    static Windows::UI::Xaml::DependencyProperty ImageProperty();
    static Windows::UI::Xaml::DependencyProperty PlaceholderImageProperty();
    static Windows::UI::Xaml::DependencyProperty PointerOverImageProperty();
    static Windows::UI::Xaml::DependencyProperty PointerOverPlaceholderImageProperty();
    static Windows::UI::Xaml::DependencyProperty UnsetImageProperty();
};

struct WINRT_EBO RatingItemInfo :
    Microsoft::UI::Xaml::Controls::IRatingItemInfo,
    impl::base<RatingItemInfo, Windows::UI::Xaml::DependencyObject>,
    impl::require<RatingItemInfo, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2>
{
    RatingItemInfo(std::nullptr_t) noexcept {}
    RatingItemInfo();
};

struct WINRT_EBO RefreshContainer :
    Microsoft::UI::Xaml::Controls::IRefreshContainer,
    impl::base<RefreshContainer, Windows::UI::Xaml::Controls::ContentControl, Windows::UI::Xaml::Controls::Control, Windows::UI::Xaml::FrameworkElement, Windows::UI::Xaml::UIElement, Windows::UI::Xaml::DependencyObject>,
    impl::require<RefreshContainer, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::Controls::IContentControl, Windows::UI::Xaml::Controls::IContentControl2, Windows::UI::Xaml::Controls::IContentControlOverrides, Windows::UI::Xaml::Controls::IControl, Windows::UI::Xaml::Controls::IControl2, Windows::UI::Xaml::Controls::IControl3, Windows::UI::Xaml::Controls::IControl4, Windows::UI::Xaml::Controls::IControl5, Windows::UI::Xaml::Controls::IControl7, Windows::UI::Xaml::Controls::IControlOverrides, Windows::UI::Xaml::Controls::IControlOverrides6, Windows::UI::Xaml::Controls::IControlProtected, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::IFrameworkElement, Windows::UI::Xaml::IFrameworkElement2, Windows::UI::Xaml::IFrameworkElement3, Windows::UI::Xaml::IFrameworkElement4, Windows::UI::Xaml::IFrameworkElement6, Windows::UI::Xaml::IFrameworkElement7, Windows::UI::Xaml::IFrameworkElementOverrides, Windows::UI::Xaml::IFrameworkElementOverrides2, Windows::UI::Xaml::IFrameworkElementProtected7, Windows::UI::Xaml::IUIElement, Windows::UI::Xaml::IUIElement2, Windows::UI::Xaml::IUIElement3, Windows::UI::Xaml::IUIElement4, Windows::UI::Xaml::IUIElement5, Windows::UI::Xaml::IUIElement7, Windows::UI::Xaml::IUIElement8, Windows::UI::Xaml::IUIElement9, Windows::UI::Xaml::IUIElementOverrides, Windows::UI::Xaml::IUIElementOverrides7, Windows::UI::Xaml::IUIElementOverrides8, Windows::UI::Xaml::IUIElementOverrides9>
{
    RefreshContainer(std::nullptr_t) noexcept {}
    RefreshContainer();
    static Windows::UI::Xaml::DependencyProperty VisualizerProperty();
    static Windows::UI::Xaml::DependencyProperty PullDirectionProperty();
};

struct WINRT_EBO RefreshInteractionRatioChangedEventArgs :
    Microsoft::UI::Xaml::Controls::IRefreshInteractionRatioChangedEventArgs
{
    RefreshInteractionRatioChangedEventArgs(std::nullptr_t) noexcept {}
};

struct WINRT_EBO RefreshRequestedEventArgs :
    Microsoft::UI::Xaml::Controls::IRefreshRequestedEventArgs
{
    RefreshRequestedEventArgs(std::nullptr_t) noexcept {}
};

struct WINRT_EBO RefreshStateChangedEventArgs :
    Microsoft::UI::Xaml::Controls::IRefreshStateChangedEventArgs
{
    RefreshStateChangedEventArgs(std::nullptr_t) noexcept {}
};

struct WINRT_EBO RefreshVisualizer :
    Microsoft::UI::Xaml::Controls::IRefreshVisualizer,
    impl::base<RefreshVisualizer, Windows::UI::Xaml::Controls::Control, Windows::UI::Xaml::FrameworkElement, Windows::UI::Xaml::UIElement, Windows::UI::Xaml::DependencyObject>,
    impl::require<RefreshVisualizer, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::Controls::IControl, Windows::UI::Xaml::Controls::IControl2, Windows::UI::Xaml::Controls::IControl3, Windows::UI::Xaml::Controls::IControl4, Windows::UI::Xaml::Controls::IControl5, Windows::UI::Xaml::Controls::IControl7, Windows::UI::Xaml::Controls::IControlOverrides, Windows::UI::Xaml::Controls::IControlOverrides6, Windows::UI::Xaml::Controls::IControlProtected, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::IFrameworkElement, Windows::UI::Xaml::IFrameworkElement2, Windows::UI::Xaml::IFrameworkElement3, Windows::UI::Xaml::IFrameworkElement4, Windows::UI::Xaml::IFrameworkElement6, Windows::UI::Xaml::IFrameworkElement7, Windows::UI::Xaml::IFrameworkElementOverrides, Windows::UI::Xaml::IFrameworkElementOverrides2, Windows::UI::Xaml::IFrameworkElementProtected7, Windows::UI::Xaml::IUIElement, Windows::UI::Xaml::IUIElement2, Windows::UI::Xaml::IUIElement3, Windows::UI::Xaml::IUIElement4, Windows::UI::Xaml::IUIElement5, Windows::UI::Xaml::IUIElement7, Windows::UI::Xaml::IUIElement8, Windows::UI::Xaml::IUIElement9, Windows::UI::Xaml::IUIElementOverrides, Windows::UI::Xaml::IUIElementOverrides7, Windows::UI::Xaml::IUIElementOverrides8, Windows::UI::Xaml::IUIElementOverrides9>
{
    RefreshVisualizer(std::nullptr_t) noexcept {}
    RefreshVisualizer();
    static Windows::UI::Xaml::DependencyProperty InfoProviderProperty();
    static Windows::UI::Xaml::DependencyProperty OrientationProperty();
    static Windows::UI::Xaml::DependencyProperty ContentProperty();
    static Windows::UI::Xaml::DependencyProperty StateProperty();
};

struct WINRT_EBO SplitButton :
    Microsoft::UI::Xaml::Controls::ISplitButton,
    impl::base<SplitButton, Windows::UI::Xaml::Controls::ContentControl, Windows::UI::Xaml::Controls::Control, Windows::UI::Xaml::FrameworkElement, Windows::UI::Xaml::UIElement, Windows::UI::Xaml::DependencyObject>,
    impl::require<SplitButton, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::Controls::IContentControl, Windows::UI::Xaml::Controls::IContentControl2, Windows::UI::Xaml::Controls::IContentControlOverrides, Windows::UI::Xaml::Controls::IControl, Windows::UI::Xaml::Controls::IControl2, Windows::UI::Xaml::Controls::IControl3, Windows::UI::Xaml::Controls::IControl4, Windows::UI::Xaml::Controls::IControl5, Windows::UI::Xaml::Controls::IControl7, Windows::UI::Xaml::Controls::IControlOverrides, Windows::UI::Xaml::Controls::IControlOverrides6, Windows::UI::Xaml::Controls::IControlProtected, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::IFrameworkElement, Windows::UI::Xaml::IFrameworkElement2, Windows::UI::Xaml::IFrameworkElement3, Windows::UI::Xaml::IFrameworkElement4, Windows::UI::Xaml::IFrameworkElement6, Windows::UI::Xaml::IFrameworkElement7, Windows::UI::Xaml::IFrameworkElementOverrides, Windows::UI::Xaml::IFrameworkElementOverrides2, Windows::UI::Xaml::IFrameworkElementProtected7, Windows::UI::Xaml::IUIElement, Windows::UI::Xaml::IUIElement2, Windows::UI::Xaml::IUIElement3, Windows::UI::Xaml::IUIElement4, Windows::UI::Xaml::IUIElement5, Windows::UI::Xaml::IUIElement7, Windows::UI::Xaml::IUIElement8, Windows::UI::Xaml::IUIElement9, Windows::UI::Xaml::IUIElementOverrides, Windows::UI::Xaml::IUIElementOverrides7, Windows::UI::Xaml::IUIElementOverrides8, Windows::UI::Xaml::IUIElementOverrides9>
{
    SplitButton(std::nullptr_t) noexcept {}
    SplitButton();
    static Windows::UI::Xaml::DependencyProperty FlyoutProperty();
    static Windows::UI::Xaml::DependencyProperty CommandProperty();
    static Windows::UI::Xaml::DependencyProperty CommandParameterProperty();
};

struct WINRT_EBO SplitButtonAutomationPeer :
    Microsoft::UI::Xaml::Controls::ISplitButtonAutomationPeer,
    impl::base<SplitButtonAutomationPeer, Windows::UI::Xaml::Automation::Peers::FrameworkElementAutomationPeer, Windows::UI::Xaml::Automation::Peers::AutomationPeer, Windows::UI::Xaml::DependencyObject>,
    impl::require<SplitButtonAutomationPeer, Windows::UI::Xaml::Automation::Peers::IAutomationPeer, Windows::UI::Xaml::Automation::Peers::IAutomationPeer2, Windows::UI::Xaml::Automation::Peers::IAutomationPeer3, Windows::UI::Xaml::Automation::Peers::IAutomationPeer4, Windows::UI::Xaml::Automation::Peers::IAutomationPeer5, Windows::UI::Xaml::Automation::Peers::IAutomationPeer6, Windows::UI::Xaml::Automation::Peers::IAutomationPeer7, Windows::UI::Xaml::Automation::Peers::IAutomationPeer8, Windows::UI::Xaml::Automation::Peers::IAutomationPeer9, Windows::UI::Xaml::Automation::Peers::IAutomationPeerOverrides, Windows::UI::Xaml::Automation::Peers::IAutomationPeerOverrides2, Windows::UI::Xaml::Automation::Peers::IAutomationPeerOverrides3, Windows::UI::Xaml::Automation::Peers::IAutomationPeerOverrides4, Windows::UI::Xaml::Automation::Peers::IAutomationPeerOverrides5, Windows::UI::Xaml::Automation::Peers::IAutomationPeerOverrides6, Windows::UI::Xaml::Automation::Peers::IAutomationPeerOverrides8, Windows::UI::Xaml::Automation::Peers::IAutomationPeerOverrides9, Windows::UI::Xaml::Automation::Peers::IAutomationPeerProtected, Windows::UI::Xaml::Automation::Peers::IFrameworkElementAutomationPeer, Windows::UI::Xaml::Automation::Provider::IExpandCollapseProvider, Windows::UI::Xaml::Automation::Provider::IInvokeProvider, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2>
{
    SplitButtonAutomationPeer(std::nullptr_t) noexcept {}
    SplitButtonAutomationPeer(Microsoft::UI::Xaml::Controls::SplitButton const& owner);
};

struct WINRT_EBO SplitButtonClickEventArgs :
    Microsoft::UI::Xaml::Controls::ISplitButtonClickEventArgs
{
    SplitButtonClickEventArgs(std::nullptr_t) noexcept {}
};

struct WINRT_EBO SwipeControl :
    Microsoft::UI::Xaml::Controls::ISwipeControl,
    impl::base<SwipeControl, Windows::UI::Xaml::Controls::ContentControl, Windows::UI::Xaml::Controls::Control, Windows::UI::Xaml::FrameworkElement, Windows::UI::Xaml::UIElement, Windows::UI::Xaml::DependencyObject>,
    impl::require<SwipeControl, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::Controls::IContentControl, Windows::UI::Xaml::Controls::IContentControl2, Windows::UI::Xaml::Controls::IContentControlOverrides, Windows::UI::Xaml::Controls::IControl, Windows::UI::Xaml::Controls::IControl2, Windows::UI::Xaml::Controls::IControl3, Windows::UI::Xaml::Controls::IControl4, Windows::UI::Xaml::Controls::IControl5, Windows::UI::Xaml::Controls::IControl7, Windows::UI::Xaml::Controls::IControlOverrides, Windows::UI::Xaml::Controls::IControlOverrides6, Windows::UI::Xaml::Controls::IControlProtected, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::IFrameworkElement, Windows::UI::Xaml::IFrameworkElement2, Windows::UI::Xaml::IFrameworkElement3, Windows::UI::Xaml::IFrameworkElement4, Windows::UI::Xaml::IFrameworkElement6, Windows::UI::Xaml::IFrameworkElement7, Windows::UI::Xaml::IFrameworkElementOverrides, Windows::UI::Xaml::IFrameworkElementOverrides2, Windows::UI::Xaml::IFrameworkElementProtected7, Windows::UI::Xaml::IUIElement, Windows::UI::Xaml::IUIElement2, Windows::UI::Xaml::IUIElement3, Windows::UI::Xaml::IUIElement4, Windows::UI::Xaml::IUIElement5, Windows::UI::Xaml::IUIElement7, Windows::UI::Xaml::IUIElement8, Windows::UI::Xaml::IUIElement9, Windows::UI::Xaml::IUIElementOverrides, Windows::UI::Xaml::IUIElementOverrides7, Windows::UI::Xaml::IUIElementOverrides8, Windows::UI::Xaml::IUIElementOverrides9>
{
    SwipeControl(std::nullptr_t) noexcept {}
    SwipeControl();
    static Windows::UI::Xaml::DependencyProperty LeftItemsProperty();
    static Windows::UI::Xaml::DependencyProperty RightItemsProperty();
    static Windows::UI::Xaml::DependencyProperty TopItemsProperty();
    static Windows::UI::Xaml::DependencyProperty BottomItemsProperty();
};

struct WINRT_EBO SwipeItem :
    Microsoft::UI::Xaml::Controls::ISwipeItem,
    impl::base<SwipeItem, Windows::UI::Xaml::DependencyObject>,
    impl::require<SwipeItem, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2>
{
    SwipeItem(std::nullptr_t) noexcept {}
    SwipeItem();
    static Windows::UI::Xaml::DependencyProperty IconSourceProperty();
    static Windows::UI::Xaml::DependencyProperty TextProperty();
    static Windows::UI::Xaml::DependencyProperty BackgroundProperty();
    static Windows::UI::Xaml::DependencyProperty ForegroundProperty();
    static Windows::UI::Xaml::DependencyProperty CommandProperty();
    static Windows::UI::Xaml::DependencyProperty CommandParameterProperty();
    static Windows::UI::Xaml::DependencyProperty BehaviorOnInvokedProperty();
};

struct WINRT_EBO SwipeItemInvokedEventArgs :
    Microsoft::UI::Xaml::Controls::ISwipeItemInvokedEventArgs
{
    SwipeItemInvokedEventArgs(std::nullptr_t) noexcept {}
};

struct WINRT_EBO SwipeItems :
    Microsoft::UI::Xaml::Controls::ISwipeItems,
    impl::base<SwipeItems, Windows::UI::Xaml::DependencyObject>,
    impl::require<SwipeItems, Windows::Foundation::Collections::IIterable<Microsoft::UI::Xaml::Controls::SwipeItem>, Windows::Foundation::Collections::IVector<Microsoft::UI::Xaml::Controls::SwipeItem>, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2>
{
    SwipeItems(std::nullptr_t) noexcept {}
    SwipeItems();
    static Windows::UI::Xaml::DependencyProperty ModeProperty();
};

struct WINRT_EBO SymbolIconSource :
    Microsoft::UI::Xaml::Controls::ISymbolIconSource,
    impl::base<SymbolIconSource, Microsoft::UI::Xaml::Controls::IconSource, Windows::UI::Xaml::DependencyObject>,
    impl::require<SymbolIconSource, Microsoft::UI::Xaml::Controls::IIconSource, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2>
{
    SymbolIconSource(std::nullptr_t) noexcept {}
    SymbolIconSource();
    static Windows::UI::Xaml::DependencyProperty SymbolProperty();
};

struct WINRT_EBO TextCommandBarFlyout :
    Microsoft::UI::Xaml::Controls::ITextCommandBarFlyout,
    impl::base<TextCommandBarFlyout, Microsoft::UI::Xaml::Controls::CommandBarFlyout, Windows::UI::Xaml::Controls::Primitives::FlyoutBase, Windows::UI::Xaml::DependencyObject>,
    impl::require<TextCommandBarFlyout, Microsoft::UI::Xaml::Controls::ICommandBarFlyout, Windows::UI::Xaml::Controls::Primitives::IFlyoutBase, Windows::UI::Xaml::Controls::Primitives::IFlyoutBase2, Windows::UI::Xaml::Controls::Primitives::IFlyoutBase3, Windows::UI::Xaml::Controls::Primitives::IFlyoutBase4, Windows::UI::Xaml::Controls::Primitives::IFlyoutBase5, Windows::UI::Xaml::Controls::Primitives::IFlyoutBaseOverrides, Windows::UI::Xaml::Controls::Primitives::IFlyoutBaseOverrides4, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2>
{
    TextCommandBarFlyout(std::nullptr_t) noexcept {}
    TextCommandBarFlyout();
    using impl::consume_t<TextCommandBarFlyout, Windows::UI::Xaml::Controls::Primitives::IFlyoutBase>::ShowAt;
    using impl::consume_t<TextCommandBarFlyout, Windows::UI::Xaml::Controls::Primitives::IFlyoutBase5>::ShowAt;
};

struct WINRT_EBO ToggleSplitButton :
    Microsoft::UI::Xaml::Controls::IToggleSplitButton,
    impl::base<ToggleSplitButton, Microsoft::UI::Xaml::Controls::SplitButton, Windows::UI::Xaml::Controls::ContentControl, Windows::UI::Xaml::Controls::Control, Windows::UI::Xaml::FrameworkElement, Windows::UI::Xaml::UIElement, Windows::UI::Xaml::DependencyObject>,
    impl::require<ToggleSplitButton, Microsoft::UI::Xaml::Controls::ISplitButton, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::Controls::IContentControl, Windows::UI::Xaml::Controls::IContentControl2, Windows::UI::Xaml::Controls::IContentControlOverrides, Windows::UI::Xaml::Controls::IControl, Windows::UI::Xaml::Controls::IControl2, Windows::UI::Xaml::Controls::IControl3, Windows::UI::Xaml::Controls::IControl4, Windows::UI::Xaml::Controls::IControl5, Windows::UI::Xaml::Controls::IControl7, Windows::UI::Xaml::Controls::IControlOverrides, Windows::UI::Xaml::Controls::IControlOverrides6, Windows::UI::Xaml::Controls::IControlProtected, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::IFrameworkElement, Windows::UI::Xaml::IFrameworkElement2, Windows::UI::Xaml::IFrameworkElement3, Windows::UI::Xaml::IFrameworkElement4, Windows::UI::Xaml::IFrameworkElement6, Windows::UI::Xaml::IFrameworkElement7, Windows::UI::Xaml::IFrameworkElementOverrides, Windows::UI::Xaml::IFrameworkElementOverrides2, Windows::UI::Xaml::IFrameworkElementProtected7, Windows::UI::Xaml::IUIElement, Windows::UI::Xaml::IUIElement2, Windows::UI::Xaml::IUIElement3, Windows::UI::Xaml::IUIElement4, Windows::UI::Xaml::IUIElement5, Windows::UI::Xaml::IUIElement7, Windows::UI::Xaml::IUIElement8, Windows::UI::Xaml::IUIElement9, Windows::UI::Xaml::IUIElementOverrides, Windows::UI::Xaml::IUIElementOverrides7, Windows::UI::Xaml::IUIElementOverrides8, Windows::UI::Xaml::IUIElementOverrides9>
{
    ToggleSplitButton(std::nullptr_t) noexcept {}
    ToggleSplitButton();
};

struct WINRT_EBO ToggleSplitButtonAutomationPeer :
    Microsoft::UI::Xaml::Controls::IToggleSplitButtonAutomationPeer,
    impl::base<ToggleSplitButtonAutomationPeer, Windows::UI::Xaml::Automation::Peers::FrameworkElementAutomationPeer, Windows::UI::Xaml::Automation::Peers::AutomationPeer, Windows::UI::Xaml::DependencyObject>,
    impl::require<ToggleSplitButtonAutomationPeer, Windows::UI::Xaml::Automation::Peers::IAutomationPeer, Windows::UI::Xaml::Automation::Peers::IAutomationPeer2, Windows::UI::Xaml::Automation::Peers::IAutomationPeer3, Windows::UI::Xaml::Automation::Peers::IAutomationPeer4, Windows::UI::Xaml::Automation::Peers::IAutomationPeer5, Windows::UI::Xaml::Automation::Peers::IAutomationPeer6, Windows::UI::Xaml::Automation::Peers::IAutomationPeer7, Windows::UI::Xaml::Automation::Peers::IAutomationPeer8, Windows::UI::Xaml::Automation::Peers::IAutomationPeer9, Windows::UI::Xaml::Automation::Peers::IAutomationPeerOverrides, Windows::UI::Xaml::Automation::Peers::IAutomationPeerOverrides2, Windows::UI::Xaml::Automation::Peers::IAutomationPeerOverrides3, Windows::UI::Xaml::Automation::Peers::IAutomationPeerOverrides4, Windows::UI::Xaml::Automation::Peers::IAutomationPeerOverrides5, Windows::UI::Xaml::Automation::Peers::IAutomationPeerOverrides6, Windows::UI::Xaml::Automation::Peers::IAutomationPeerOverrides8, Windows::UI::Xaml::Automation::Peers::IAutomationPeerOverrides9, Windows::UI::Xaml::Automation::Peers::IAutomationPeerProtected, Windows::UI::Xaml::Automation::Peers::IFrameworkElementAutomationPeer, Windows::UI::Xaml::Automation::Provider::IExpandCollapseProvider, Windows::UI::Xaml::Automation::Provider::IToggleProvider, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2>
{
    ToggleSplitButtonAutomationPeer(std::nullptr_t) noexcept {}
    ToggleSplitButtonAutomationPeer(Microsoft::UI::Xaml::Controls::ToggleSplitButton const& owner);
};

struct WINRT_EBO ToggleSplitButtonIsCheckedChangedEventArgs :
    Microsoft::UI::Xaml::Controls::IToggleSplitButtonIsCheckedChangedEventArgs
{
    ToggleSplitButtonIsCheckedChangedEventArgs(std::nullptr_t) noexcept {}
};

struct WINRT_EBO TreeView :
    Microsoft::UI::Xaml::Controls::ITreeView,
    impl::base<TreeView, Windows::UI::Xaml::Controls::Control, Windows::UI::Xaml::FrameworkElement, Windows::UI::Xaml::UIElement, Windows::UI::Xaml::DependencyObject>,
    impl::require<TreeView, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::Controls::IControl, Windows::UI::Xaml::Controls::IControl2, Windows::UI::Xaml::Controls::IControl3, Windows::UI::Xaml::Controls::IControl4, Windows::UI::Xaml::Controls::IControl5, Windows::UI::Xaml::Controls::IControl7, Windows::UI::Xaml::Controls::IControlOverrides, Windows::UI::Xaml::Controls::IControlOverrides6, Windows::UI::Xaml::Controls::IControlProtected, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::IFrameworkElement, Windows::UI::Xaml::IFrameworkElement2, Windows::UI::Xaml::IFrameworkElement3, Windows::UI::Xaml::IFrameworkElement4, Windows::UI::Xaml::IFrameworkElement6, Windows::UI::Xaml::IFrameworkElement7, Windows::UI::Xaml::IFrameworkElementOverrides, Windows::UI::Xaml::IFrameworkElementOverrides2, Windows::UI::Xaml::IFrameworkElementProtected7, Windows::UI::Xaml::IUIElement, Windows::UI::Xaml::IUIElement2, Windows::UI::Xaml::IUIElement3, Windows::UI::Xaml::IUIElement4, Windows::UI::Xaml::IUIElement5, Windows::UI::Xaml::IUIElement7, Windows::UI::Xaml::IUIElement8, Windows::UI::Xaml::IUIElement9, Windows::UI::Xaml::IUIElementOverrides, Windows::UI::Xaml::IUIElementOverrides7, Windows::UI::Xaml::IUIElementOverrides8, Windows::UI::Xaml::IUIElementOverrides9>
{
    TreeView(std::nullptr_t) noexcept {}
    TreeView();
    static Windows::UI::Xaml::DependencyProperty SelectionModeProperty();
    static Windows::UI::Xaml::DependencyProperty CanDragItemsProperty();
    static Windows::UI::Xaml::DependencyProperty CanReorderItemsProperty();
    static Windows::UI::Xaml::DependencyProperty ItemTemplateProperty();
    static Windows::UI::Xaml::DependencyProperty ItemTemplateSelectorProperty();
    static Windows::UI::Xaml::DependencyProperty ItemContainerStyleProperty();
    static Windows::UI::Xaml::DependencyProperty ItemContainerStyleSelectorProperty();
    static Windows::UI::Xaml::DependencyProperty ItemContainerTransitionsProperty();
    static Windows::UI::Xaml::DependencyProperty ItemsSourceProperty();
};

struct WINRT_EBO TreeViewCollapsedEventArgs :
    Microsoft::UI::Xaml::Controls::ITreeViewCollapsedEventArgs
{
    TreeViewCollapsedEventArgs(std::nullptr_t) noexcept {}
};

struct WINRT_EBO TreeViewDragItemsCompletedEventArgs :
    Microsoft::UI::Xaml::Controls::ITreeViewDragItemsCompletedEventArgs
{
    TreeViewDragItemsCompletedEventArgs(std::nullptr_t) noexcept {}
};

struct WINRT_EBO TreeViewDragItemsStartingEventArgs :
    Microsoft::UI::Xaml::Controls::ITreeViewDragItemsStartingEventArgs
{
    TreeViewDragItemsStartingEventArgs(std::nullptr_t) noexcept {}
};

struct WINRT_EBO TreeViewExpandingEventArgs :
    Microsoft::UI::Xaml::Controls::ITreeViewExpandingEventArgs
{
    TreeViewExpandingEventArgs(std::nullptr_t) noexcept {}
};

struct WINRT_EBO TreeViewItem :
    Microsoft::UI::Xaml::Controls::ITreeViewItem,
    impl::base<TreeViewItem, Windows::UI::Xaml::Controls::ListViewItem, Windows::UI::Xaml::Controls::Primitives::SelectorItem, Windows::UI::Xaml::Controls::ContentControl, Windows::UI::Xaml::Controls::Control, Windows::UI::Xaml::FrameworkElement, Windows::UI::Xaml::UIElement, Windows::UI::Xaml::DependencyObject>,
    impl::require<TreeViewItem, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::Controls::IContentControl, Windows::UI::Xaml::Controls::IContentControl2, Windows::UI::Xaml::Controls::IContentControlOverrides, Windows::UI::Xaml::Controls::IControl, Windows::UI::Xaml::Controls::IControl2, Windows::UI::Xaml::Controls::IControl3, Windows::UI::Xaml::Controls::IControl4, Windows::UI::Xaml::Controls::IControl5, Windows::UI::Xaml::Controls::IControl7, Windows::UI::Xaml::Controls::IControlOverrides, Windows::UI::Xaml::Controls::IControlOverrides6, Windows::UI::Xaml::Controls::IControlProtected, Windows::UI::Xaml::Controls::IListViewItem, Windows::UI::Xaml::Controls::Primitives::ISelectorItem, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::IFrameworkElement, Windows::UI::Xaml::IFrameworkElement2, Windows::UI::Xaml::IFrameworkElement3, Windows::UI::Xaml::IFrameworkElement4, Windows::UI::Xaml::IFrameworkElement6, Windows::UI::Xaml::IFrameworkElement7, Windows::UI::Xaml::IFrameworkElementOverrides, Windows::UI::Xaml::IFrameworkElementOverrides2, Windows::UI::Xaml::IFrameworkElementProtected7, Windows::UI::Xaml::IUIElement, Windows::UI::Xaml::IUIElement2, Windows::UI::Xaml::IUIElement3, Windows::UI::Xaml::IUIElement4, Windows::UI::Xaml::IUIElement5, Windows::UI::Xaml::IUIElement7, Windows::UI::Xaml::IUIElement8, Windows::UI::Xaml::IUIElement9, Windows::UI::Xaml::IUIElementOverrides, Windows::UI::Xaml::IUIElementOverrides7, Windows::UI::Xaml::IUIElementOverrides8, Windows::UI::Xaml::IUIElementOverrides9>
{
    TreeViewItem(std::nullptr_t) noexcept {}
    TreeViewItem();
    static Windows::UI::Xaml::DependencyProperty GlyphOpacityProperty();
    static Windows::UI::Xaml::DependencyProperty GlyphBrushProperty();
    static Windows::UI::Xaml::DependencyProperty ExpandedGlyphProperty();
    static Windows::UI::Xaml::DependencyProperty CollapsedGlyphProperty();
    static Windows::UI::Xaml::DependencyProperty GlyphSizeProperty();
    static Windows::UI::Xaml::DependencyProperty IsExpandedProperty();
    static Windows::UI::Xaml::DependencyProperty TreeViewItemTemplateSettingsProperty();
    static Windows::UI::Xaml::DependencyProperty HasUnrealizedChildrenProperty();
    static Windows::UI::Xaml::DependencyProperty ItemsSourceProperty();
};

struct WINRT_EBO TreeViewItemInvokedEventArgs :
    Microsoft::UI::Xaml::Controls::ITreeViewItemInvokedEventArgs
{
    TreeViewItemInvokedEventArgs(std::nullptr_t) noexcept {}
};

struct WINRT_EBO TreeViewItemTemplateSettings :
    Microsoft::UI::Xaml::Controls::ITreeViewItemTemplateSettings,
    impl::base<TreeViewItemTemplateSettings, Windows::UI::Xaml::DependencyObject>,
    impl::require<TreeViewItemTemplateSettings, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2>
{
    TreeViewItemTemplateSettings(std::nullptr_t) noexcept {}
    TreeViewItemTemplateSettings();
    static Windows::UI::Xaml::DependencyProperty ExpandedGlyphVisibilityProperty();
    static Windows::UI::Xaml::DependencyProperty CollapsedGlyphVisibilityProperty();
    static Windows::UI::Xaml::DependencyProperty IndentationProperty();
    static Windows::UI::Xaml::DependencyProperty DragItemsCountProperty();
};

struct WINRT_EBO TreeViewList :
    Microsoft::UI::Xaml::Controls::ITreeViewList,
    impl::base<TreeViewList, Windows::UI::Xaml::Controls::ListView, Windows::UI::Xaml::Controls::ListViewBase, Windows::UI::Xaml::Controls::Primitives::Selector, Windows::UI::Xaml::Controls::ItemsControl, Windows::UI::Xaml::Controls::Control, Windows::UI::Xaml::FrameworkElement, Windows::UI::Xaml::UIElement, Windows::UI::Xaml::DependencyObject>,
    impl::require<TreeViewList, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::Controls::IControl, Windows::UI::Xaml::Controls::IControl2, Windows::UI::Xaml::Controls::IControl3, Windows::UI::Xaml::Controls::IControl4, Windows::UI::Xaml::Controls::IControl5, Windows::UI::Xaml::Controls::IControl7, Windows::UI::Xaml::Controls::IControlOverrides, Windows::UI::Xaml::Controls::IControlOverrides6, Windows::UI::Xaml::Controls::IControlProtected, Windows::UI::Xaml::Controls::IItemContainerMapping, Windows::UI::Xaml::Controls::IItemsControl, Windows::UI::Xaml::Controls::IItemsControl2, Windows::UI::Xaml::Controls::IItemsControl3, Windows::UI::Xaml::Controls::IItemsControlOverrides, Windows::UI::Xaml::Controls::IListView, Windows::UI::Xaml::Controls::IListViewBase, Windows::UI::Xaml::Controls::IListViewBase2, Windows::UI::Xaml::Controls::IListViewBase3, Windows::UI::Xaml::Controls::IListViewBase4, Windows::UI::Xaml::Controls::IListViewBase5, Windows::UI::Xaml::Controls::IListViewBase6, Windows::UI::Xaml::Controls::ISemanticZoomInformation, Windows::UI::Xaml::Controls::Primitives::ISelector, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::IFrameworkElement, Windows::UI::Xaml::IFrameworkElement2, Windows::UI::Xaml::IFrameworkElement3, Windows::UI::Xaml::IFrameworkElement4, Windows::UI::Xaml::IFrameworkElement6, Windows::UI::Xaml::IFrameworkElement7, Windows::UI::Xaml::IFrameworkElementOverrides, Windows::UI::Xaml::IFrameworkElementOverrides2, Windows::UI::Xaml::IFrameworkElementProtected7, Windows::UI::Xaml::IUIElement, Windows::UI::Xaml::IUIElement2, Windows::UI::Xaml::IUIElement3, Windows::UI::Xaml::IUIElement4, Windows::UI::Xaml::IUIElement5, Windows::UI::Xaml::IUIElement7, Windows::UI::Xaml::IUIElement8, Windows::UI::Xaml::IUIElement9, Windows::UI::Xaml::IUIElementOverrides, Windows::UI::Xaml::IUIElementOverrides7, Windows::UI::Xaml::IUIElementOverrides8, Windows::UI::Xaml::IUIElementOverrides9>
{
    TreeViewList(std::nullptr_t) noexcept {}
    TreeViewList();
};

struct WINRT_EBO TreeViewNode :
    Microsoft::UI::Xaml::Controls::ITreeViewNode,
    impl::base<TreeViewNode, Windows::UI::Xaml::DependencyObject>,
    impl::require<TreeViewNode, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2>
{
    TreeViewNode(std::nullptr_t) noexcept {}
    TreeViewNode();
    static Windows::UI::Xaml::DependencyProperty ContentProperty();
    static Windows::UI::Xaml::DependencyProperty DepthProperty();
    static Windows::UI::Xaml::DependencyProperty IsExpandedProperty();
    static Windows::UI::Xaml::DependencyProperty HasChildrenProperty();
};

struct WINRT_EBO XamlControlsResources :
    Microsoft::UI::Xaml::Controls::IXamlControlsResources,
    impl::base<XamlControlsResources, Windows::UI::Xaml::ResourceDictionary, Windows::UI::Xaml::DependencyObject>,
    impl::require<XamlControlsResources, Windows::Foundation::Collections::IIterable<Windows::Foundation::Collections::IKeyValuePair<Windows::Foundation::IInspectable, Windows::Foundation::IInspectable>>, Windows::Foundation::Collections::IMap<Windows::Foundation::IInspectable, Windows::Foundation::IInspectable>, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::IResourceDictionary>
{
    XamlControlsResources(std::nullptr_t) noexcept {}
    XamlControlsResources();
    static void EnsureRevealLights(Windows::UI::Xaml::UIElement const& element);
};

}
