// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/Windows.UI.Xaml.Interop.1.h"
#include "winrt/impl/Windows.UI.Xaml.Markup.1.h"
#include "Microsoft.UI.Xaml.XamlTypeInfo.1.h"

WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::XamlTypeInfo {

}

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::XamlTypeInfo {

struct WINRT_EBO XamlControlsXamlMetaDataProvider :
    Windows::UI::Xaml::Markup::IXamlMetadataProvider,
    impl::require<XamlControlsXamlMetaDataProvider, Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsXamlMetaDataProvider>
{
    XamlControlsXamlMetaDataProvider(std::nullptr_t) noexcept {}
    XamlControlsXamlMetaDataProvider();
    static void Initialize();
};

}
