// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once

#include "winrt/Windows.Storage.h"
#include "winrt/Windows.Storage.FileProperties.h"
#include "winrt/Windows.UI.Xaml.h"
#include "winrt/Windows.UI.Xaml.Data.h"
#include "winrt/Windows.UI.Xaml.Interop.h"
#include "winrt/Windows.UI.Xaml.Markup.h"
#include "winrt/Windows.UI.Xaml.Media.Imaging.h"
#include "winrt/Windows.UI.Composition.h"
#include "winrt/Windows.UI.Xaml.Controls.h"
#include "winrt/Windows.UI.Xaml.Media.h"
#include "winrt/SimplePhotoViewer.h"

namespace winrt::SimplePhotoViewer::implementation {

template <typename D, typename... I>
struct WINRT_EBO BackdropSaturationBrush_base : implements<D, SimplePhotoViewer::IBackdropSaturationBrush, Windows::UI::Xaml::Media::IBrushOverrides2, Windows::UI::Xaml::Media::IXamlCompositionBrushBaseOverrides, composing, I...>,
    impl::require<D, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::Media::IBrush, Windows::UI::Xaml::Media::IXamlCompositionBrushBase, Windows::UI::Xaml::Media::IXamlCompositionBrushBaseProtected>,
    impl::base<D, Windows::UI::Xaml::Media::XamlCompositionBrushBase, Windows::UI::Xaml::Media::Brush, Windows::UI::Xaml::DependencyObject>,
    Windows::UI::Xaml::Media::IBrushOverrides2T<D>, Windows::UI::Xaml::Media::IXamlCompositionBrushBaseOverridesT<D>
{
    using base_type = BackdropSaturationBrush_base;
    using class_type = SimplePhotoViewer::BackdropSaturationBrush;
    using implements_type = typename BackdropSaturationBrush_base::implements_type;
    using implements_type::implements_type;
    using composable_base = Windows::UI::Xaml::Media::XamlCompositionBrushBase;
#if _MSC_VER < 1914
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename impl::implements_default_interface<D>::type, default_interface<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<default_interface<class_type>>(*this)));
        return result;
    }
#else
    operator impl::producer_ref<class_type> const() const noexcept
    {
        return { to_abi<default_interface<class_type>>(this) };
    }
#endif

    hstring GetRuntimeClassName() const
    {
        return L"SimplePhotoViewer.BackdropSaturationBrush";
    }
    BackdropSaturationBrush_base()
    {
        impl::call_factory<Windows::UI::Xaml::Media::XamlCompositionBrushBase, Windows::UI::Xaml::Media::IXamlCompositionBrushBaseFactory>([&](auto&& f) { f.CreateInstance(*this, this->m_inner); });
    }
};

}

namespace winrt::SimplePhotoViewer::factory_implementation {

template <typename D, typename T, typename... I>
struct WINRT_EBO BackdropSaturationBrushT : implements<D, Windows::Foundation::IActivationFactory, SimplePhotoViewer::IBackdropSaturationBrushStatics, I...>
{
    using instance_type = SimplePhotoViewer::BackdropSaturationBrush;

    hstring GetRuntimeClassName() const
    {
        return L"SimplePhotoViewer.BackdropSaturationBrush";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        return make<T>();
    }

    Windows::UI::Xaml::DependencyProperty SaturationProperty()
    {
        return T::SaturationProperty();
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_BACKDROPSATURATIONBRUSH_XAML_G_H) || __has_include("BackdropSaturationBrush.xaml.g.h")

#include "BackdropSaturationBrush.xaml.g.h"

#else

namespace winrt::SimplePhotoViewer::implementation
{
    template <typename D, typename... I>
    using BackdropSaturationBrushT = BackdropSaturationBrush_base<D, I...>;
}

#endif
