//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include "XamlBindingInfo.xaml.g.h"

namespace winrt::SimplePhotoViewer::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct DetailPageT : public ::winrt::SimplePhotoViewer::implementation::DetailPage_base<D,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector2,
        I...>
    {
        using base_type = typename DetailPageT::base_type;
        using base_type::base_type;
        using class_type = typename DetailPageT::class_type;

        void InitializeComponent();
        void Connect(int32_t connectionId, IInspectable const& target);
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Windows::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Windows::UI::Xaml::Controls::Grid Display()
        {
            return _Display;
        }
        void Display(::winrt::Windows::UI::Xaml::Controls::Grid value)
        {
            _Display = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Grid Tooler()
        {
            return _Tooler;
        }
        void Tooler(::winrt::Windows::UI::Xaml::Controls::Grid value)
        {
            _Tooler = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::ContentDialog ImageContentDialog()
        {
            return _ImageContentDialog;
        }
        void ImageContentDialog(::winrt::Windows::UI::Xaml::Controls::ContentDialog value)
        {
            _ImageContentDialog = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::AppBarButton SlidePlay()
        {
            return _SlidePlay;
        }
        void SlidePlay(::winrt::Windows::UI::Xaml::Controls::AppBarButton value)
        {
            _SlidePlay = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::AppBarButton SlidePause()
        {
            return _SlidePause;
        }
        void SlidePause(::winrt::Windows::UI::Xaml::Controls::AppBarButton value)
        {
            _SlidePause = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::AppBarButton ZoomInAppBarButton()
        {
            return _ZoomInAppBarButton;
        }
        void ZoomInAppBarButton(::winrt::Windows::UI::Xaml::Controls::AppBarButton value)
        {
            _ZoomInAppBarButton = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::AppBarButton ZoomOutAppBarButton()
        {
            return _ZoomOutAppBarButton;
        }
        void ZoomOutAppBarButton(::winrt::Windows::UI::Xaml::Controls::AppBarButton value)
        {
            _ZoomOutAppBarButton = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::AppBarButton RotateAppBarButton()
        {
            return _RotateAppBarButton;
        }
        void RotateAppBarButton(::winrt::Windows::UI::Xaml::Controls::AppBarButton value)
        {
            _RotateAppBarButton = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::AppBarButton CancelAppBarButton()
        {
            return _CancelAppBarButton;
        }
        void CancelAppBarButton(::winrt::Windows::UI::Xaml::Controls::AppBarButton value)
        {
            _CancelAppBarButton = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::AppBarButton EditAppBarButton()
        {
            return _EditAppBarButton;
        }
        void EditAppBarButton(::winrt::Windows::UI::Xaml::Controls::AppBarButton value)
        {
            _EditAppBarButton = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::AppBarButton SaveAppBarButton()
        {
            return _SaveAppBarButton;
        }
        void SaveAppBarButton(::winrt::Windows::UI::Xaml::Controls::AppBarButton value)
        {
            _SaveAppBarButton = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::CheckBox TaTCheckBox2()
        {
            return _TaTCheckBox2;
        }
        void TaTCheckBox2(::winrt::Windows::UI::Xaml::Controls::CheckBox value)
        {
            _TaTCheckBox2 = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::CheckBox TaTCheckBox()
        {
            return _TaTCheckBox;
        }
        void TaTCheckBox(::winrt::Windows::UI::Xaml::Controls::CheckBox value)
        {
            _TaTCheckBox = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::CheckBox SepiaCheckBox()
        {
            return _SepiaCheckBox;
        }
        void SepiaCheckBox(::winrt::Windows::UI::Xaml::Controls::CheckBox value)
        {
            _SepiaCheckBox = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::CheckBox SaturationCheckBox()
        {
            return _SaturationCheckBox;
        }
        void SaturationCheckBox(::winrt::Windows::UI::Xaml::Controls::CheckBox value)
        {
            _SaturationCheckBox = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::CheckBox ExposureCheckBox()
        {
            return _ExposureCheckBox;
        }
        void ExposureCheckBox(::winrt::Windows::UI::Xaml::Controls::CheckBox value)
        {
            _ExposureCheckBox = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::CheckBox BlurCheckBox()
        {
            return _BlurCheckBox;
        }
        void BlurCheckBox(::winrt::Windows::UI::Xaml::Controls::CheckBox value)
        {
            _BlurCheckBox = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::ScrollViewer FlipViewScrollViewer()
        {
            return _FlipViewScrollViewer;
        }
        void FlipViewScrollViewer(::winrt::Windows::UI::Xaml::Controls::ScrollViewer value)
        {
            _FlipViewScrollViewer = value;
        }

        ::winrt::Windows::UI::Xaml::Shapes::Rectangle rtg()
        {
            return _rtg;
        }
        void rtg(::winrt::Windows::UI::Xaml::Shapes::Rectangle value)
        {
            _rtg = value;
        }

        ::winrt::Windows::UI::Xaml::Shapes::Rectangle rtgexp()
        {
            return _rtgexp;
        }
        void rtgexp(::winrt::Windows::UI::Xaml::Shapes::Rectangle value)
        {
            _rtgexp = value;
        }

        ::winrt::Windows::UI::Xaml::Shapes::Rectangle rtgsat()
        {
            return _rtgsat;
        }
        void rtgsat(::winrt::Windows::UI::Xaml::Shapes::Rectangle value)
        {
            _rtgsat = value;
        }

        ::winrt::Windows::UI::Xaml::Shapes::Rectangle rtgsep()
        {
            return _rtgsep;
        }
        void rtgsep(::winrt::Windows::UI::Xaml::Shapes::Rectangle value)
        {
            _rtgsep = value;
        }

        ::winrt::Windows::UI::Xaml::Shapes::Rectangle rtgtem()
        {
            return _rtgtem;
        }
        void rtgtem(::winrt::Windows::UI::Xaml::Shapes::Rectangle value)
        {
            _rtgtem = value;
        }

        ::winrt::Windows::UI::Xaml::Shapes::Rectangle test()
        {
            return _test;
        }
        void test(::winrt::Windows::UI::Xaml::Shapes::Rectangle value)
        {
            _test = value;
        }

        ::winrt::Windows::UI::Xaml::Media::ImageBrush testBrush()
        {
            return _testBrush;
        }
        void testBrush(::winrt::Windows::UI::Xaml::Media::ImageBrush value)
        {
            _testBrush = value;
        }

        ::winrt::SimplePhotoViewer::BackdropTemperatureAndTintBrush bshtemp()
        {
            return _bshtemp;
        }
        void bshtemp(::winrt::SimplePhotoViewer::BackdropTemperatureAndTintBrush value)
        {
            _bshtemp = value;
        }

        ::winrt::SimplePhotoViewer::BackdropSepiaBrush bshsep()
        {
            return _bshsep;
        }
        void bshsep(::winrt::SimplePhotoViewer::BackdropSepiaBrush value)
        {
            _bshsep = value;
        }

        ::winrt::SimplePhotoViewer::BackdropSaturationBrush bshsat()
        {
            return _bshsat;
        }
        void bshsat(::winrt::SimplePhotoViewer::BackdropSaturationBrush value)
        {
            _bshsat = value;
        }

        ::winrt::SimplePhotoViewer::BackdropExposureBrush bshexp()
        {
            return _bshexp;
        }
        void bshexp(::winrt::SimplePhotoViewer::BackdropExposureBrush value)
        {
            _bshexp = value;
        }

        ::winrt::SimplePhotoViewer::BackdropBlurBrush bsh()
        {
            return _bsh;
        }
        void bsh(::winrt::SimplePhotoViewer::BackdropBlurBrush value)
        {
            _bsh = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::FlipView DetailPageFlipView()
        {
            return _DetailPageFlipView;
        }
        void DetailPageFlipView(::winrt::Windows::UI::Xaml::Controls::FlipView value)
        {
            _DetailPageFlipView = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::ScrollViewer ThumbnailScrollViewer()
        {
            return _ThumbnailScrollViewer;
        }
        void ThumbnailScrollViewer(::winrt::Windows::UI::Xaml::Controls::ScrollViewer value)
        {
            _ThumbnailScrollViewer = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::ListView ThumbnailListView()
        {
            return _ThumbnailListView;
        }
        void ThumbnailListView(::winrt::Windows::UI::Xaml::Controls::ListView value)
        {
            _ThumbnailListView = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Grid FolderPath()
        {
            return _FolderPath;
        }
        void FolderPath(::winrt::Windows::UI::Xaml::Controls::Grid value)
        {
            _FolderPath = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::AppBarButton Thumbnail()
        {
            return _Thumbnail;
        }
        void Thumbnail(::winrt::Windows::UI::Xaml::Controls::AppBarButton value)
        {
            _Thumbnail = value;
        }
        
         ::winrt::com_ptr<::winrt::SimplePhotoViewer::implementation::XamlBindings> Bindings;

    protected:
        bool _contentLoaded{false};

    private:
        struct DetailPage_obj39_Bindings;
        struct DetailPage_obj44_Bindings;
        struct DetailPage_obj1_Bindings;

        ::winrt::Windows::UI::Xaml::Controls::Grid _Display{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Grid _Tooler{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::ContentDialog _ImageContentDialog{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::AppBarButton _SlidePlay{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::AppBarButton _SlidePause{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::AppBarButton _ZoomInAppBarButton{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::AppBarButton _ZoomOutAppBarButton{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::AppBarButton _RotateAppBarButton{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::AppBarButton _CancelAppBarButton{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::AppBarButton _EditAppBarButton{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::AppBarButton _SaveAppBarButton{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::CheckBox _TaTCheckBox2{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::CheckBox _TaTCheckBox{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::CheckBox _SepiaCheckBox{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::CheckBox _SaturationCheckBox{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::CheckBox _ExposureCheckBox{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::CheckBox _BlurCheckBox{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::ScrollViewer _FlipViewScrollViewer{nullptr};
        ::winrt::Windows::UI::Xaml::Shapes::Rectangle _rtg{nullptr};
        ::winrt::Windows::UI::Xaml::Shapes::Rectangle _rtgexp{nullptr};
        ::winrt::Windows::UI::Xaml::Shapes::Rectangle _rtgsat{nullptr};
        ::winrt::Windows::UI::Xaml::Shapes::Rectangle _rtgsep{nullptr};
        ::winrt::Windows::UI::Xaml::Shapes::Rectangle _rtgtem{nullptr};
        ::winrt::Windows::UI::Xaml::Shapes::Rectangle _test{nullptr};
        ::winrt::Windows::UI::Xaml::Media::ImageBrush _testBrush{nullptr};
        ::winrt::SimplePhotoViewer::BackdropTemperatureAndTintBrush _bshtemp{nullptr};
        ::winrt::SimplePhotoViewer::BackdropSepiaBrush _bshsep{nullptr};
        ::winrt::SimplePhotoViewer::BackdropSaturationBrush _bshsat{nullptr};
        ::winrt::SimplePhotoViewer::BackdropExposureBrush _bshexp{nullptr};
        ::winrt::SimplePhotoViewer::BackdropBlurBrush _bsh{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::FlipView _DetailPageFlipView{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::ScrollViewer _ThumbnailScrollViewer{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::ListView _ThumbnailListView{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Grid _FolderPath{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::AppBarButton _Thumbnail{nullptr};
    };
}

