//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include "XamlBindingInfo.xaml.g.h"

namespace winrt::SimplePhotoViewer::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct DetailPageT : public ::winrt::SimplePhotoViewer::implementation::DetailPage_base<D,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector2,
        I...>
    {
        using base_type = typename DetailPageT::base_type;
        using base_type::base_type;
        using class_type = typename DetailPageT::class_type;

        void InitializeComponent();
        void Connect(int32_t connectionId, IInspectable const& target);
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Windows::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Windows::UI::Xaml::Controls::ScrollViewer ThumbnailScrollViewer()
        {
            return _ThumbnailScrollViewer;
        }
        void ThumbnailScrollViewer(::winrt::Windows::UI::Xaml::Controls::ScrollViewer value)
        {
            _ThumbnailScrollViewer = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::ListView ThumbnailListView()
        {
            return _ThumbnailListView;
        }
        void ThumbnailListView(::winrt::Windows::UI::Xaml::Controls::ListView value)
        {
            _ThumbnailListView = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::FlipView DetailPageFlipView()
        {
            return _DetailPageFlipView;
        }
        void DetailPageFlipView(::winrt::Windows::UI::Xaml::Controls::FlipView value)
        {
            _DetailPageFlipView = value;
        }
        
         ::winrt::com_ptr<::winrt::SimplePhotoViewer::implementation::XamlBindings> Bindings;

    protected:
        bool _contentLoaded{false};

    private:
        struct DetailPage_obj4_Bindings;
        struct DetailPage_obj6_Bindings;
        struct DetailPage_obj1_Bindings;

        ::winrt::Windows::UI::Xaml::Controls::ScrollViewer _ThumbnailScrollViewer{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::ListView _ThumbnailListView{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::FlipView _DetailPageFlipView{nullptr};
    };
}

