//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include "XamlBindingInfo.xaml.g.h"

namespace winrt::SimplePhotoViewer::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct DetailPageT : public ::winrt::SimplePhotoViewer::implementation::DetailPage_base<D,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector2,
        I...>
    {
        using base_type = typename DetailPageT::base_type;
        using base_type::base_type;
        using class_type = typename DetailPageT::class_type;

        void InitializeComponent();
        void Connect(int32_t connectionId, IInspectable const& target);
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Windows::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Windows::UI::Xaml::Controls::Grid Display()
        {
            return _Display;
        }
        void Display(::winrt::Windows::UI::Xaml::Controls::Grid value)
        {
            _Display = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Grid Tooler()
        {
            return _Tooler;
        }
        void Tooler(::winrt::Windows::UI::Xaml::Controls::Grid value)
        {
            _Tooler = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Button SlidePlay()
        {
            return _SlidePlay;
        }
        void SlidePlay(::winrt::Windows::UI::Xaml::Controls::Button value)
        {
            _SlidePlay = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Button ThePreviousPicture()
        {
            return _ThePreviousPicture;
        }
        void ThePreviousPicture(::winrt::Windows::UI::Xaml::Controls::Button value)
        {
            _ThePreviousPicture = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Button TheLatterPicture()
        {
            return _TheLatterPicture;
        }
        void TheLatterPicture(::winrt::Windows::UI::Xaml::Controls::Button value)
        {
            _TheLatterPicture = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Button Enlarge()
        {
            return _Enlarge;
        }
        void Enlarge(::winrt::Windows::UI::Xaml::Controls::Button value)
        {
            _Enlarge = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Button Reduce()
        {
            return _Reduce;
        }
        void Reduce(::winrt::Windows::UI::Xaml::Controls::Button value)
        {
            _Reduce = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Button Counterclockwise()
        {
            return _Counterclockwise;
        }
        void Counterclockwise(::winrt::Windows::UI::Xaml::Controls::Button value)
        {
            _Counterclockwise = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Button Clockwise()
        {
            return _Clockwise;
        }
        void Clockwise(::winrt::Windows::UI::Xaml::Controls::Button value)
        {
            _Clockwise = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Button Edit()
        {
            return _Edit;
        }
        void Edit(::winrt::Windows::UI::Xaml::Controls::Button value)
        {
            _Edit = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Button Information()
        {
            return _Information;
        }
        void Information(::winrt::Windows::UI::Xaml::Controls::Button value)
        {
            _Information = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Button OpenFile()
        {
            return _OpenFile;
        }
        void OpenFile(::winrt::Windows::UI::Xaml::Controls::Button value)
        {
            _OpenFile = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Button Maker()
        {
            return _Maker;
        }
        void Maker(::winrt::Windows::UI::Xaml::Controls::Button value)
        {
            _Maker = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::FlipView DetailPageFlipView()
        {
            return _DetailPageFlipView;
        }
        void DetailPageFlipView(::winrt::Windows::UI::Xaml::Controls::FlipView value)
        {
            _DetailPageFlipView = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::ScrollViewer ThumbnailScrollViewer()
        {
            return _ThumbnailScrollViewer;
        }
        void ThumbnailScrollViewer(::winrt::Windows::UI::Xaml::Controls::ScrollViewer value)
        {
            _ThumbnailScrollViewer = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::ListView ThumbnailListView()
        {
            return _ThumbnailListView;
        }
        void ThumbnailListView(::winrt::Windows::UI::Xaml::Controls::ListView value)
        {
            _ThumbnailListView = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Grid FolderPath()
        {
            return _FolderPath;
        }
        void FolderPath(::winrt::Windows::UI::Xaml::Controls::Grid value)
        {
            _FolderPath = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::AppBarButton Thumbnail()
        {
            return _Thumbnail;
        }
        void Thumbnail(::winrt::Windows::UI::Xaml::Controls::AppBarButton value)
        {
            _Thumbnail = value;
        }
        
         ::winrt::com_ptr<::winrt::SimplePhotoViewer::implementation::XamlBindings> Bindings;

    protected:
        bool _contentLoaded{false};

    private:
        struct DetailPage_obj16_Bindings;
        struct DetailPage_obj20_Bindings;
        struct DetailPage_obj1_Bindings;

        ::winrt::Windows::UI::Xaml::Controls::Grid _Display{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Grid _Tooler{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Button _SlidePlay{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Button _ThePreviousPicture{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Button _TheLatterPicture{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Button _Enlarge{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Button _Reduce{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Button _Counterclockwise{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Button _Clockwise{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Button _Edit{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Button _Information{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Button _OpenFile{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Button _Maker{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::FlipView _DetailPageFlipView{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::ScrollViewer _ThumbnailScrollViewer{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::ListView _ThumbnailListView{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Grid _FolderPath{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::AppBarButton _Thumbnail{nullptr};
    };
}

