//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "MainPage.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

namespace winrt::SimplePhotoViewer::implementation
{
    using Application = ::winrt::Windows::UI::Xaml::Application;
    using ComponentResourceLocation = ::winrt::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation;
    using DataTemplate = ::winrt::Windows::UI::Xaml::DataTemplate;
    using DependencyObject = ::winrt::Windows::UI::Xaml::DependencyObject;
    using DependencyProperty = ::winrt::Windows::UI::Xaml::DependencyProperty;
    using IComponentConnector = ::winrt::Windows::UI::Xaml::Markup::IComponentConnector;
    using Uri = ::winrt::Windows::Foundation::Uri;
    using XamlBindingHelper = ::winrt::Windows::UI::Xaml::Markup::XamlBindingHelper;

    template <typename D, typename ... I>
    void MainPageT<D, I...>::InitializeComponent()
    {
        if (!_contentLoaded)
        {
            _contentLoaded = true;
            Uri resourceLocator{ L"ms-appx:///MainPage.xaml" };
            Application::LoadComponent(*this, resourceLocator, ComponentResourceLocation::Application);
        }
    }

    template <typename D, typename ... I>
    void MainPageT<D, I...>::Connect(int32_t connectionId, IInspectable const& target)
    {
        switch (connectionId)
        {
        case 3:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::Image>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.DoubleTapped([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->GridViewItem_DoubleTapped(p0, p1);
                    }
                });
            }
            break;
        case 10:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::SplitView>();
                this->splitView(targetElement);
            }
            break;
        case 11:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::Grid>();
                this->TopLeftGrid(targetElement);
            }
            break;
        case 12:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::Grid>();
                this->TreeView_Grid(targetElement);
            }
            break;
        case 13:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::ListView>();
                this->ListView2(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.ItemClick([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Windows::UI::Xaml::Controls::ItemClickEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->SelectionListView_ItemClicked(p0, p1);
                    }
                });
            }
            break;
        case 14:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TreeView>();
                this->DirectoryTreeView(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Expanding([weakThis](::winrt::Microsoft::UI::Xaml::Controls::TreeView const& p0, ::winrt::Microsoft::UI::Xaml::Controls::TreeViewExpandingEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->DirectoryItem_Expanding(p0, p1);
                    }
                });
                targetElement.Collapsed([weakThis](::winrt::Microsoft::UI::Xaml::Controls::TreeView const& p0, ::winrt::Microsoft::UI::Xaml::Controls::TreeViewCollapsedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->DirectoryItem_Collapsed(p0, p1);
                    }
                });
                targetElement.ItemInvoked([weakThis](::winrt::Microsoft::UI::Xaml::Controls::TreeView const& p0, ::winrt::Microsoft::UI::Xaml::Controls::TreeViewItemInvokedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->DirectoryItem_Invoked(p0, p1);
                    }
                });
            }
            break;
        case 15:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::ListView>();
                this->ListView1(targetElement);
            }
            break;
        case 16:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::Button>();
                this->SplitView_Button(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Windows::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->SplitViewButton_ClickHandler(p0, p1);
                    }
                });
            }
            break;
        case 17:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::TextBlock>();
                this->SimplePhotoViewer_TextBlock(targetElement);
            }
            break;
        case 18:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::RelativePanel>();
                this->Windows_RelativePanel(targetElement);
            }
            break;
        case 19:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::Grid>();
                this->PointerDetectedGrid(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.PointerPressed([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Windows::UI::Xaml::Input::PointerRoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->Windows_MouseDown(p0, p1);
                    }
                });
                targetElement.PointerMoved([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Windows::UI::Xaml::Input::PointerRoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->Windows_MouseHold(p0, p1);
                    }
                });
                targetElement.PointerReleased([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Windows::UI::Xaml::Input::PointerRoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->Windows_MouseUp(p0, p1);
                    }
                });
            }
            break;
        case 20:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::Canvas>();
                this->dragSelectionCanvas(targetElement);
            }
            break;
        case 21:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::Border>();
                this->dragSelectionBorder(targetElement);
            }
            break;
        case 22:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::Grid>();
                this->TitleGrid(targetElement);
            }
            break;
        case 23:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::Grid>();
                this->DisplayGrid(targetElement);
            }
            break;
        case 24:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::StackPanel>();
                this->Deleteme_StackPanel(targetElement);
            }
            break;
        case 27:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::Button>();
                this->SlidePlay(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Windows::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->SlidePlay_ClickHandler(p0, p1);
                    }
                });
            }
            break;
        case 28:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::AppBarButton>();
                this->CopyAppBarButton(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Windows::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->Copy_ClickHandler(p0, p1);
                    }
                });
            }
            break;
        case 29:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::AppBarButton>();
                this->ShearAppBarButton(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Windows::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->Shear_ClickHandler(p0, p1);
                    }
                });
            }
            break;
        case 30:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::AppBarButton>();
                this->PasteAppBarButton(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Windows::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->Paste_ClickHandler(p0, p1);
                    }
                });
            }
            break;
        case 31:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::AppBarButton>();
                this->DeleteAppBarButton(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Windows::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->Delete_ClickHandler(p0, p1);
                    }
                });
            }
            break;
        case 32:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::AppBarButton>();
                this->RenameButton(targetElement);
            }
            break;
        case 33:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::AppBarButton>();
                this->OpenAppBarButton(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Windows::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->OpenFile_ClickHandler(p0, p1);
                    }
                });
            }
            break;
        case 34:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::TextBox>();
                this->nameInput(targetElement);
            }
            break;
        case 35:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::TextBox>();
                this->FirstCode(targetElement);
            }
            break;
        case 36:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::TextBox>();
                this->DigitNum(targetElement);
            }
            break;
        case 37:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::Button>();
                this->Rename(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Windows::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->Rename_ClickHandler(p0, p1);
                    }
                });
            }
            break;
        case 38:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::GridView>();
                this->ImageGridView(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.SelectionChanged([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Windows::UI::Xaml::Controls::SelectionChangedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->GridViewItem_SelectionChanged(p0, p1);
                    }
                });
                targetElement.ContainerContentChanging([weakThis](::winrt::Windows::UI::Xaml::Controls::ListViewBase const& p0, ::winrt::Windows::UI::Xaml::Controls::ContainerContentChangingEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->OnContainerContentChanging(p0, p1);
                    }
                });
            }
            break;
        case 39:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::AutoSuggestBox>();
                this->SearchAutoSuggetsBox(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.SuggestionChosen([weakThis](::winrt::Windows::UI::Xaml::Controls::AutoSuggestBox const& p0, ::winrt::Windows::UI::Xaml::Controls::AutoSuggestBoxSuggestionChosenEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->SearchBox_SuggestionChosen(p0, p1);
                    }
                });
                targetElement.TextChanged([weakThis](::winrt::Windows::UI::Xaml::Controls::AutoSuggestBox const& p0, ::winrt::Windows::UI::Xaml::Controls::AutoSuggestBoxTextChangedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->SearchBox_TextChanged(p0, p1);
                    }
                });
                targetElement.QuerySubmitted([weakThis](::winrt::Windows::UI::Xaml::Controls::AutoSuggestBox const& p0, ::winrt::Windows::UI::Xaml::Controls::AutoSuggestBoxQuerySubmittedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->SearchBox_QuerySubmitted(p0, p1);
                    }
                });
            }
            break;
        case 41:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::Grid>();
                this->RealFolderPath_Grid(targetElement);
            }
            break;
        case 43:
            {
                auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::Button>();
                this->ParentFolderButton(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Windows::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->ParentFolderButton_ClickHandler(p0, p1);
                    }
                });
            }
            break;
        }
        _contentLoaded = true;
    }

    template <typename D, typename ... I>
    void MainPageT<D, I...>::DisconnectUnloadedObject(int32_t)
    {
        throw ::winrt::hresult_invalid_argument { L"No unloadable objects to disconnect." };
    }

    template <typename D, typename ... I>
    void MainPageT<D, I...>::UnloadObject(DependencyObject const&)
    {
        throw ::winrt::hresult_invalid_argument { L"No unloadable objects." };
    }

    template <typename D, typename... I>
    IComponentConnector MainPageT<D, I...>::GetBindingConnector(int32_t connectionId, IInspectable const& target)
    {
        ::winrt::com_ptr<::winrt::SimplePhotoViewer::implementation::XamlBindings> bindings;
        switch (connectionId)
        {
            case 1: // MainPage.xaml line 1
                {
                    auto element1 = target.as<::winrt::Windows::UI::Xaml::Controls::Page>();
                    auto objBindings = std::make_unique<MainPage_obj1_Bindings>();
                    objBindings->SetDataRoot(*this);
                    bindings = ::winrt::make_self<::winrt::SimplePhotoViewer::implementation::XamlBindings>(std::move(objBindings));
                    Bindings = bindings;
                    element1.Loading({&*bindings, &::winrt::SimplePhotoViewer::implementation::XamlBindings::Loading});
                }
                break;
            case 2: // MainPage.xaml line 40
                {
                    auto element2 = target.as<::winrt::Windows::UI::Xaml::Controls::StackPanel>();
                    auto objBindings = std::make_unique<MainPage_obj2_Bindings>();
                    objBindings->SetDataRoot(element2.DataContext());
                    bindings = ::winrt::make_self<::winrt::SimplePhotoViewer::implementation::XamlBindings>(std::move(objBindings));
                    bindings->SubscribeForDataContextChanged(element2);
                    DataTemplate::SetExtensionInstance(element2, bindings.as<::winrt::Windows::UI::Xaml::IDataTemplateExtension>());
                    XamlBindingHelper::SetDataTemplateComponent(element2, bindings.as<::winrt::Windows::UI::Xaml::Markup::IDataTemplateComponent>());
                }
                break;
            case 6: // MainPage.xaml line 27
                {
                    auto element6 = target.as<::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem>();
                    auto objBindings = std::make_unique<MainPage_obj6_Bindings>();
                    objBindings->SetDataRoot(element6.DataContext());
                    bindings = ::winrt::make_self<::winrt::SimplePhotoViewer::implementation::XamlBindings>(std::move(objBindings));
                    bindings->SubscribeForDataContextChanged(element6);
                    DataTemplate::SetExtensionInstance(element6, bindings.as<::winrt::Windows::UI::Xaml::IDataTemplateExtension>());
                    XamlBindingHelper::SetDataTemplateComponent(element6, bindings.as<::winrt::Windows::UI::Xaml::Markup::IDataTemplateComponent>());
                }
                break;
            case 8: // MainPage.xaml line 15
                {
                    auto element8 = target.as<::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem>();
                    auto objBindings = std::make_unique<MainPage_obj8_Bindings>();
                    objBindings->SetDataRoot(element8.DataContext());
                    bindings = ::winrt::make_self<::winrt::SimplePhotoViewer::implementation::XamlBindings>(std::move(objBindings));
                    bindings->SubscribeForDataContextChanged(element8);
                    DataTemplate::SetExtensionInstance(element8, bindings.as<::winrt::Windows::UI::Xaml::IDataTemplateExtension>());
                    XamlBindingHelper::SetDataTemplateComponent(element8, bindings.as<::winrt::Windows::UI::Xaml::Markup::IDataTemplateComponent>());
                }
                break;
            case 40: // MainPage.xaml line 244
                {
                    auto element40 = target.as<::winrt::Windows::UI::Xaml::Controls::TextBlock>();
                    auto objBindings = std::make_unique<MainPage_obj40_Bindings>();
                    objBindings->SetDataRoot(element40.DataContext());
                    bindings = ::winrt::make_self<::winrt::SimplePhotoViewer::implementation::XamlBindings>(std::move(objBindings));
                    bindings->SubscribeForDataContextChanged(element40);
                    DataTemplate::SetExtensionInstance(element40, bindings.as<::winrt::Windows::UI::Xaml::IDataTemplateExtension>());
                    XamlBindingHelper::SetDataTemplateComponent(element40, bindings.as<::winrt::Windows::UI::Xaml::Markup::IDataTemplateComponent>());
                }
                break;
        }
        return bindings ? bindings.as<::winrt::Windows::UI::Xaml::Markup::IComponentConnector>() : nullptr;
    }

    template <typename D, typename ... I>
    struct MainPageT<D, I...>::MainPage_obj2_Bindings
        : public ::winrt::SimplePhotoViewer::implementation::ReferenceTypeXamlBindings<::winrt::SimplePhotoViewer::ImageSku, ::winrt::SimplePhotoViewer::implementation::XamlBindingTrackingBase>
        , public ::winrt::SimplePhotoViewer::implementation::IXamlBindingTracking
{
        MainPage_obj2_Bindings()
        {
            InitializeTracking(this);
        }

        ~MainPage_obj2_Bindings()
        {
            ReleaseAllListeners();
        }

        void Connect(int32_t connectionId, IInspectable const& target) override
        {
            switch(connectionId)
            {
            case 2: // MainPage.xaml line 40
                {
                    auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::StackPanel>();
                    obj2 = targetElement;
                }
                break;
            case 3: // MainPage.xaml line 41
                {
                    auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::Image>();
                    obj3 = targetElement;
                }
                break;
            case 4: // MainPage.xaml line 48
                {
                    auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::TextBlock>();
                    obj4 = targetElement;
                }
                break;
            case 5: // MainPage.xaml line 45
                {
                    auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::ToolTip>();
                    obj5 = targetElement;
                }
                break;
            }
        }

        void DisconnectUnloadedObject(int connectionId) override
        {
            throw ::winrt::hresult_invalid_argument { L"No unloadable elements to disconnect." };
        }

        void Recycle() override
        {
            ReleaseAllListeners();
        }

        void ProcessBindings(IInspectable const& item, int itemIndex, int phase, int32_t& nextPhase)
        {
            nextPhase = -1;
            switch (phase)
            {
            case 0:
                {
                    nextPhase = -1;
                    SetDataRoot(item);
                    if (_dataContextChangedToken.value != 0)
                    {
                        this->obj2.get().DataContextChanged(_dataContextChangedToken);
                        _dataContextChangedToken.value = 0;
                    }
                    _isInitialized = true;
                 }
                 break;
            }
            Update_(::winrt::unbox_value<::winrt::SimplePhotoViewer::ImageSku>(item) , 1 << phase);
        }


    private:
        // Fields for each control that has bindings.
        ::winrt::weak_ref<::winrt::Windows::UI::Xaml::Controls::StackPanel> obj2;
        ::winrt::Windows::UI::Xaml::Controls::Image obj3 { nullptr };
        ::winrt::Windows::UI::Xaml::Controls::TextBlock obj4 { nullptr };
        ::winrt::Windows::UI::Xaml::Controls::ToolTip obj5 { nullptr };

        // Fields for binding tracking.
        ::winrt::weak_ref<::winrt::Windows::UI::Xaml::Data::INotifyPropertyChanged> cachePC_;
        ::winrt::event_token tokenPC_ {};

        // Update methods for each path node used in binding steps.

        void Update_(::winrt::SimplePhotoViewer::ImageSku obj, int32_t phase)
        {
            _bindingsTracking->UpdatePropertyChangedListener(obj, cachePC_, tokenPC_);
            if (obj)
            {
                if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
                {
                    Update_ImageThumbnail(obj.ImageThumbnail(), phase);
                    Update_ImageNameWithType(obj.ImageNameWithType(), phase);
                    Update_ImageName(obj.ImageName(), phase);
                }
            }
        }

        void Update_ImageThumbnail(::winrt::Windows::UI::Xaml::Media::Imaging::BitmapImage obj, int32_t phase)
        {
            if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
            {
                // MainPage.xaml line 41
                Set_Windows_UI_Xaml_Controls_Image_Source(obj3, obj, std::nullopt);
            }
        }

        void Update_ImageNameWithType(::winrt::hstring obj, int32_t phase)
        {
            if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
            {
                // MainPage.xaml line 48
                Set_Windows_UI_Xaml_Controls_TextBlock_Text(obj4, obj);
            }
        }

        void Update_ImageName(::winrt::hstring obj, int32_t phase)
        {
            if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
            {
                // MainPage.xaml line 45
                Set_Windows_UI_Xaml_Controls_ContentControl_Content(obj5, ::winrt::box_value(obj), std::nullopt);
            }
        }

        virtual void ReleaseAllListeners() override
        {
            _bindingsTracking->UpdatePropertyChangedListener(nullptr, cachePC_, tokenPC_);
        }

        virtual void PropertyChanged(IInspectable const& sender, ::winrt::Windows::UI::Xaml::Data::PropertyChangedEventArgs const& e) override
        {
            if (GetDataRoot() && GetDataRoot() == sender)
            {
                auto propName = e.PropertyName();
                auto obj = sender.as<::winrt::SimplePhotoViewer::ImageSku>();
                if (propName.empty())
                {
                    if (obj)
                    {
                        Update_ImageThumbnail(obj.ImageThumbnail(), DATA_CHANGED);
                        Update_ImageNameWithType(obj.ImageNameWithType(), DATA_CHANGED);
                        Update_ImageName(obj.ImageName(), DATA_CHANGED);
                    }
                }
                else if (propName == L"ImageThumbnail")
                {
                    if (obj)
                    {
                        Update_ImageThumbnail(obj.ImageThumbnail(), DATA_CHANGED);
                    }
                }
                else if (propName == L"ImageNameWithType")
                {
                    if (obj)
                    {
                        Update_ImageNameWithType(obj.ImageNameWithType(), DATA_CHANGED);
                    }
                }
                else if (propName == L"ImageName")
                {
                    if (obj)
                    {
                        Update_ImageName(obj.ImageName(), DATA_CHANGED);
                    }
                }
            }
        }

        void CollectionChanged(IInspectable const& sender, ::winrt::Windows::UI::Xaml::Interop::NotifyCollectionChangedEventArgs const& e) override
        {
        }

        void VectorChanged(IInspectable const& sender, ::winrt::Windows::Foundation::Collections::IVectorChangedEventArgs const& e) override
        {
        }

        void MapChanged(IInspectable const& sender, ::winrt::Windows::Foundation::Collections::IMapChangedEventArgs<::winrt::hstring> const& e) override
        {
        }

        void DependencyPropertyChanged(DependencyObject const& sender, DependencyProperty const& prop) override
        {
            if (sender)
            {
            }
        }


        static void Set_Windows_UI_Xaml_Controls_Image_Source(::winrt::Windows::UI::Xaml::Controls::Image const& obj, ::winrt::Windows::UI::Xaml::Media::ImageSource value, std::optional<::winrt::hstring> const& targetNullValue)
        {
            if (!value && targetNullValue)
            {
                value = ::winrt::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::winrt::xaml_typename<::winrt::Windows::UI::Xaml::Media::ImageSource>(), ::winrt::box_value(::winrt::hstring(targetNullValue.value()))).as<::winrt::Windows::UI::Xaml::Media::ImageSource>();
            }
            obj.Source(value);
        }

        static void Set_Windows_UI_Xaml_Controls_TextBlock_Text(::winrt::Windows::UI::Xaml::Controls::TextBlock const& obj, ::winrt::hstring const& value)
        {
            obj.Text(value);
        }

        static void Set_Windows_UI_Xaml_Controls_ContentControl_Content(::winrt::Windows::UI::Xaml::Controls::ContentControl const& obj, ::winrt::Windows::Foundation::IInspectable value, std::optional<::winrt::hstring> const& targetNullValue)
        {
            if (!value && targetNullValue)
            {
                value = ::winrt::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::winrt::xaml_typename<::winrt::Windows::Foundation::IInspectable>(), ::winrt::box_value(::winrt::hstring(targetNullValue.value()))).as<::winrt::Windows::Foundation::IInspectable>();
            }
            obj.Content(value);
        }
    }; 

    struct MainPage_obj6_BindingsTracking : public XamlBindingTrackingBase
    {
        MainPage_obj6_BindingsTracking()
        {}

        // Event handlers

        void VectorChanged_Object(
            ::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable> const& sender,
            ::winrt::Windows::Foundation::Collections::IVectorChangedEventArgs const& e)
        {
            VectorChanged(sender, e);
        }

        // Listener update functions

        void UpdateVectorChangedListener_Object(
            ::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable> const& obj,
            ::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable> & cache,
            ::winrt::event_token token)
        {
            if (cache && cache != obj)
            {
                cache.VectorChanged(token);
                cache = nullptr;
            }
            if (!cache && obj)
            {
                cache = obj;
                token = obj.VectorChanged({this, &MainPage_obj6_BindingsTracking::VectorChanged_Object});
            }
        }
    };

    template <typename D, typename ... I>
    struct MainPageT<D, I...>::MainPage_obj6_Bindings
        : public ::winrt::SimplePhotoViewer::implementation::ReferenceTypeXamlBindings<::winrt::SimplePhotoViewer::DirectoryItem, MainPage_obj6_BindingsTracking>
        , public ::winrt::SimplePhotoViewer::implementation::IXamlBindingTracking
{
        MainPage_obj6_Bindings()
        {
            InitializeTracking(this);
        }

        ~MainPage_obj6_Bindings()
        {
            ReleaseAllListeners();
        }

        void Connect(int32_t connectionId, IInspectable const& target) override
        {
            switch(connectionId)
            {
            case 6: // MainPage.xaml line 27
                {
                    auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem>();
                    obj6 = targetElement;
                }
                break;
            case 7: // MainPage.xaml line 34
                {
                    auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::TextBlock>();
                    obj7 = targetElement;
                }
                break;
            }
        }

        void DisconnectUnloadedObject(int connectionId) override
        {
            throw ::winrt::hresult_invalid_argument { L"No unloadable elements to disconnect." };
        }

        void Recycle() override
        {
            ReleaseAllListeners();
        }

        void ProcessBindings(IInspectable const& item, int itemIndex, int phase, int32_t& nextPhase)
        {
            nextPhase = -1;
            switch (phase)
            {
            case 0:
                {
                    nextPhase = -1;
                    SetDataRoot(item);
                    if (_dataContextChangedToken.value != 0)
                    {
                        this->obj6.get().DataContextChanged(_dataContextChangedToken);
                        _dataContextChangedToken.value = 0;
                    }
                    _isInitialized = true;
                 }
                 break;
            }
            Update_(::winrt::unbox_value<::winrt::SimplePhotoViewer::DirectoryItem>(item) , 1 << phase);
        }


    private:
        // Fields for each control that has bindings.
        ::winrt::weak_ref<::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem> obj6;
        ::winrt::Windows::UI::Xaml::Controls::TextBlock obj7 { nullptr };

        // Fields for binding tracking.
        ::winrt::weak_ref<::winrt::Windows::UI::Xaml::Data::INotifyPropertyChanged> cachePC_;
        ::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable> cacheVC_SubItems{nullptr};
        ::winrt::event_token tokenPC_ {};
        ::winrt::event_token tokenVC_SubItems {};

        // Update methods for each path node used in binding steps.

        void Update_(::winrt::SimplePhotoViewer::DirectoryItem obj, int32_t phase)
        {
            _bindingsTracking->UpdatePropertyChangedListener(obj, cachePC_, tokenPC_);
            if (obj)
            {
                if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
                {
                    Update_SubItems(obj.SubItems(), phase);
                }
                if ((phase & (NOT_PHASED | (1 << 0))) != 0)
                {
                    Update_Item(obj.Item(), phase);
                }
            }
        }

        void Update_SubItems(::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable> obj, int32_t phase)
        {
            _bindingsTracking->UpdateVectorChangedListener_Object(obj, cacheVC_SubItems, tokenVC_SubItems);
            if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
            {
                // MainPage.xaml line 27
                if (obj6)
                {
                    Set_Microsoft_UI_Xaml_Controls_TreeViewItem_ItemsSource(this->obj6.get(), obj, std::nullopt);
                }
            }
        }

        void Update_Item(::winrt::hstring obj, int32_t phase)
        {
            if((phase & ((1 << 0) | NOT_PHASED )) != 0)
            {
                // MainPage.xaml line 34
                Set_Windows_UI_Xaml_Controls_TextBlock_Text(obj7, obj);
            }
        }

        virtual void ReleaseAllListeners() override
        {
            _bindingsTracking->UpdatePropertyChangedListener(nullptr, cachePC_, tokenPC_);
            _bindingsTracking->UpdateVectorChangedListener_Object(nullptr, cacheVC_SubItems, tokenVC_SubItems);
        }

        virtual void PropertyChanged(IInspectable const& sender, ::winrt::Windows::UI::Xaml::Data::PropertyChangedEventArgs const& e) override
        {
            if (GetDataRoot() && GetDataRoot() == sender)
            {
                auto propName = e.PropertyName();
                auto obj = sender.as<::winrt::SimplePhotoViewer::DirectoryItem>();
                if (propName.empty())
                {
                    if (obj)
                    {
                        Update_SubItems(obj.SubItems(), DATA_CHANGED);
                    }
                }
                else if (propName == L"SubItems")
                {
                    if (obj)
                    {
                        Update_SubItems(obj.SubItems(), DATA_CHANGED);
                    }
                }
            }
        }

        void CollectionChanged(IInspectable const& sender, ::winrt::Windows::UI::Xaml::Interop::NotifyCollectionChangedEventArgs const& e) override
        {
        }

        void VectorChanged(IInspectable const& sender, ::winrt::Windows::Foundation::Collections::IVectorChangedEventArgs const& e) override
        {
            if (cacheVC_SubItems && cacheVC_SubItems == sender)
            {
                ::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable> obj = sender.as<::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable>>();
            }
        }

        void MapChanged(IInspectable const& sender, ::winrt::Windows::Foundation::Collections::IMapChangedEventArgs<::winrt::hstring> const& e) override
        {
        }

        void DependencyPropertyChanged(DependencyObject const& sender, DependencyProperty const& prop) override
        {
            if (sender)
            {
            }
        }


        static void Set_Microsoft_UI_Xaml_Controls_TreeViewItem_ItemsSource(::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem const& obj, ::winrt::Windows::Foundation::IInspectable value, std::optional<::winrt::hstring> const& targetNullValue)
        {
            if (!value && targetNullValue)
            {
                value = ::winrt::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::winrt::xaml_typename<::winrt::Windows::Foundation::IInspectable>(), ::winrt::box_value(::winrt::hstring(targetNullValue.value()))).as<::winrt::Windows::Foundation::IInspectable>();
            }
            obj.ItemsSource(value);
        }

        static void Set_Windows_UI_Xaml_Controls_TextBlock_Text(::winrt::Windows::UI::Xaml::Controls::TextBlock const& obj, ::winrt::hstring const& value)
        {
            obj.Text(value);
        }
    }; 

    struct MainPage_obj8_BindingsTracking : public XamlBindingTrackingBase
    {
        MainPage_obj8_BindingsTracking()
        {}

        // Event handlers

        void VectorChanged_Object(
            ::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable> const& sender,
            ::winrt::Windows::Foundation::Collections::IVectorChangedEventArgs const& e)
        {
            VectorChanged(sender, e);
        }

        // Listener update functions

        void UpdateVectorChangedListener_Object(
            ::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable> const& obj,
            ::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable> & cache,
            ::winrt::event_token token)
        {
            if (cache && cache != obj)
            {
                cache.VectorChanged(token);
                cache = nullptr;
            }
            if (!cache && obj)
            {
                cache = obj;
                token = obj.VectorChanged({this, &MainPage_obj8_BindingsTracking::VectorChanged_Object});
            }
        }
    };

    template <typename D, typename ... I>
    struct MainPageT<D, I...>::MainPage_obj8_Bindings
        : public ::winrt::SimplePhotoViewer::implementation::ReferenceTypeXamlBindings<::winrt::SimplePhotoViewer::DirectoryItem, MainPage_obj8_BindingsTracking>
        , public ::winrt::SimplePhotoViewer::implementation::IXamlBindingTracking
{
        MainPage_obj8_Bindings()
        {
            InitializeTracking(this);
        }

        ~MainPage_obj8_Bindings()
        {
            ReleaseAllListeners();
        }

        void Connect(int32_t connectionId, IInspectable const& target) override
        {
            switch(connectionId)
            {
            case 8: // MainPage.xaml line 15
                {
                    auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem>();
                    obj8 = targetElement;
                }
                break;
            case 9: // MainPage.xaml line 22
                {
                    auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::TextBlock>();
                    obj9 = targetElement;
                }
                break;
            }
        }

        void DisconnectUnloadedObject(int connectionId) override
        {
            throw ::winrt::hresult_invalid_argument { L"No unloadable elements to disconnect." };
        }

        void Recycle() override
        {
            ReleaseAllListeners();
        }

        void ProcessBindings(IInspectable const& item, int itemIndex, int phase, int32_t& nextPhase)
        {
            nextPhase = -1;
            switch (phase)
            {
            case 0:
                {
                    nextPhase = -1;
                    SetDataRoot(item);
                    if (_dataContextChangedToken.value != 0)
                    {
                        this->obj8.get().DataContextChanged(_dataContextChangedToken);
                        _dataContextChangedToken.value = 0;
                    }
                    _isInitialized = true;
                 }
                 break;
            }
            Update_(::winrt::unbox_value<::winrt::SimplePhotoViewer::DirectoryItem>(item) , 1 << phase);
        }


    private:
        // Fields for each control that has bindings.
        ::winrt::weak_ref<::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem> obj8;
        ::winrt::Windows::UI::Xaml::Controls::TextBlock obj9 { nullptr };

        // Fields for binding tracking.
        ::winrt::weak_ref<::winrt::Windows::UI::Xaml::Data::INotifyPropertyChanged> cachePC_;
        ::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable> cacheVC_SubItems{nullptr};
        ::winrt::event_token tokenPC_ {};
        ::winrt::event_token tokenVC_SubItems {};

        // Update methods for each path node used in binding steps.

        void Update_(::winrt::SimplePhotoViewer::DirectoryItem obj, int32_t phase)
        {
            _bindingsTracking->UpdatePropertyChangedListener(obj, cachePC_, tokenPC_);
            if (obj)
            {
                if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
                {
                    Update_SubItems(obj.SubItems(), phase);
                }
                if ((phase & (NOT_PHASED | (1 << 0))) != 0)
                {
                    Update_Item(obj.Item(), phase);
                }
            }
        }

        void Update_SubItems(::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable> obj, int32_t phase)
        {
            _bindingsTracking->UpdateVectorChangedListener_Object(obj, cacheVC_SubItems, tokenVC_SubItems);
            if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
            {
                // MainPage.xaml line 15
                if (obj8)
                {
                    Set_Microsoft_UI_Xaml_Controls_TreeViewItem_ItemsSource(this->obj8.get(), obj, std::nullopt);
                }
            }
        }

        void Update_Item(::winrt::hstring obj, int32_t phase)
        {
            if((phase & ((1 << 0) | NOT_PHASED )) != 0)
            {
                // MainPage.xaml line 22
                Set_Windows_UI_Xaml_Controls_TextBlock_Text(obj9, obj);
            }
        }

        virtual void ReleaseAllListeners() override
        {
            _bindingsTracking->UpdatePropertyChangedListener(nullptr, cachePC_, tokenPC_);
            _bindingsTracking->UpdateVectorChangedListener_Object(nullptr, cacheVC_SubItems, tokenVC_SubItems);
        }

        virtual void PropertyChanged(IInspectable const& sender, ::winrt::Windows::UI::Xaml::Data::PropertyChangedEventArgs const& e) override
        {
            if (GetDataRoot() && GetDataRoot() == sender)
            {
                auto propName = e.PropertyName();
                auto obj = sender.as<::winrt::SimplePhotoViewer::DirectoryItem>();
                if (propName.empty())
                {
                    if (obj)
                    {
                        Update_SubItems(obj.SubItems(), DATA_CHANGED);
                    }
                }
                else if (propName == L"SubItems")
                {
                    if (obj)
                    {
                        Update_SubItems(obj.SubItems(), DATA_CHANGED);
                    }
                }
            }
        }

        void CollectionChanged(IInspectable const& sender, ::winrt::Windows::UI::Xaml::Interop::NotifyCollectionChangedEventArgs const& e) override
        {
        }

        void VectorChanged(IInspectable const& sender, ::winrt::Windows::Foundation::Collections::IVectorChangedEventArgs const& e) override
        {
            if (cacheVC_SubItems && cacheVC_SubItems == sender)
            {
                ::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable> obj = sender.as<::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable>>();
            }
        }

        void MapChanged(IInspectable const& sender, ::winrt::Windows::Foundation::Collections::IMapChangedEventArgs<::winrt::hstring> const& e) override
        {
        }

        void DependencyPropertyChanged(DependencyObject const& sender, DependencyProperty const& prop) override
        {
            if (sender)
            {
            }
        }


        static void Set_Microsoft_UI_Xaml_Controls_TreeViewItem_ItemsSource(::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem const& obj, ::winrt::Windows::Foundation::IInspectable value, std::optional<::winrt::hstring> const& targetNullValue)
        {
            if (!value && targetNullValue)
            {
                value = ::winrt::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::winrt::xaml_typename<::winrt::Windows::Foundation::IInspectable>(), ::winrt::box_value(::winrt::hstring(targetNullValue.value()))).as<::winrt::Windows::Foundation::IInspectable>();
            }
            obj.ItemsSource(value);
        }

        static void Set_Windows_UI_Xaml_Controls_TextBlock_Text(::winrt::Windows::UI::Xaml::Controls::TextBlock const& obj, ::winrt::hstring const& value)
        {
            obj.Text(value);
        }
    }; 

    template <typename D, typename ... I>
    struct MainPageT<D, I...>::MainPage_obj40_Bindings
        : public ::winrt::SimplePhotoViewer::implementation::ReferenceTypeXamlBindings<::winrt::SimplePhotoViewer::ImageSku, ::winrt::SimplePhotoViewer::implementation::XamlBindingTrackingBase>
        , public ::winrt::SimplePhotoViewer::implementation::IXamlBindingTracking
{
        MainPage_obj40_Bindings()
        {
            InitializeTracking(this);
        }

        ~MainPage_obj40_Bindings()
        {
            ReleaseAllListeners();
        }

        void Connect(int32_t connectionId, IInspectable const& target) override
        {
            switch(connectionId)
            {
            case 40: // MainPage.xaml line 244
                {
                    auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::TextBlock>();
                    obj40 = targetElement;
                }
                break;
            }
        }

        void DisconnectUnloadedObject(int connectionId) override
        {
            throw ::winrt::hresult_invalid_argument { L"No unloadable elements to disconnect." };
        }

        void Recycle() override
        {
            ReleaseAllListeners();
        }

        void ProcessBindings(IInspectable const& item, int itemIndex, int phase, int32_t& nextPhase)
        {
            nextPhase = -1;
            switch (phase)
            {
            case 0:
                {
                    nextPhase = -1;
                    SetDataRoot(item);
                    if (_dataContextChangedToken.value != 0)
                    {
                        this->obj40.get().DataContextChanged(_dataContextChangedToken);
                        _dataContextChangedToken.value = 0;
                    }
                    _isInitialized = true;
                 }
                 break;
            }
            Update_(::winrt::unbox_value<::winrt::SimplePhotoViewer::ImageSku>(item) , 1 << phase);
        }


    private:
        // Fields for each control that has bindings.
        ::winrt::weak_ref<::winrt::Windows::UI::Xaml::Controls::TextBlock> obj40;

        // Fields for binding tracking.
        ::winrt::weak_ref<::winrt::Windows::UI::Xaml::Data::INotifyPropertyChanged> cachePC_;
        ::winrt::event_token tokenPC_ {};

        // Update methods for each path node used in binding steps.

        void Update_(::winrt::SimplePhotoViewer::ImageSku obj, int32_t phase)
        {
            _bindingsTracking->UpdatePropertyChangedListener(obj, cachePC_, tokenPC_);
            if (obj)
            {
                if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
                {
                    Update_ImageNameWithType(obj.ImageNameWithType(), phase);
                }
            }
        }

        void Update_ImageNameWithType(::winrt::hstring obj, int32_t phase)
        {
            if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
            {
                // MainPage.xaml line 244
                if (obj40)
                {
                    Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj40.get(), obj);
                }
            }
        }

        virtual void ReleaseAllListeners() override
        {
            _bindingsTracking->UpdatePropertyChangedListener(nullptr, cachePC_, tokenPC_);
        }

        virtual void PropertyChanged(IInspectable const& sender, ::winrt::Windows::UI::Xaml::Data::PropertyChangedEventArgs const& e) override
        {
            if (GetDataRoot() && GetDataRoot() == sender)
            {
                auto propName = e.PropertyName();
                auto obj = sender.as<::winrt::SimplePhotoViewer::ImageSku>();
                if (propName.empty())
                {
                    if (obj)
                    {
                        Update_ImageNameWithType(obj.ImageNameWithType(), DATA_CHANGED);
                    }
                }
                else if (propName == L"ImageNameWithType")
                {
                    if (obj)
                    {
                        Update_ImageNameWithType(obj.ImageNameWithType(), DATA_CHANGED);
                    }
                }
            }
        }

        void CollectionChanged(IInspectable const& sender, ::winrt::Windows::UI::Xaml::Interop::NotifyCollectionChangedEventArgs const& e) override
        {
        }

        void VectorChanged(IInspectable const& sender, ::winrt::Windows::Foundation::Collections::IVectorChangedEventArgs const& e) override
        {
        }

        void MapChanged(IInspectable const& sender, ::winrt::Windows::Foundation::Collections::IMapChangedEventArgs<::winrt::hstring> const& e) override
        {
        }

        void DependencyPropertyChanged(DependencyObject const& sender, DependencyProperty const& prop) override
        {
            if (sender)
            {
            }
        }


        static void Set_Windows_UI_Xaml_Controls_TextBlock_Text(::winrt::Windows::UI::Xaml::Controls::TextBlock const& obj, ::winrt::hstring const& value)
        {
            obj.Text(value);
        }
    }; 

    struct MainPage_obj1_BindingsTracking : public XamlBindingTrackingBase
    {
        MainPage_obj1_BindingsTracking()
        {}

        // Event handlers

        void VectorChanged_Object(
            ::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable> const& sender,
            ::winrt::Windows::Foundation::Collections::IVectorChangedEventArgs const& e)
        {
            VectorChanged(sender, e);
        }

        // Listener update functions

        void UpdateVectorChangedListener_Object(
            ::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable> const& obj,
            ::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable> & cache,
            ::winrt::event_token token)
        {
            if (cache && cache != obj)
            {
                cache.VectorChanged(token);
                cache = nullptr;
            }
            if (!cache && obj)
            {
                cache = obj;
                token = obj.VectorChanged({this, &MainPage_obj1_BindingsTracking::VectorChanged_Object});
            }
        }
    };

    template <typename D, typename ... I>
    struct MainPageT<D, I...>::MainPage_obj1_Bindings
        : public ::winrt::SimplePhotoViewer::implementation::ReferenceTypeXamlBindings<::winrt::SimplePhotoViewer::MainPage, MainPage_obj1_BindingsTracking>
        , public ::winrt::SimplePhotoViewer::implementation::IXamlBindingTracking
{
        MainPage_obj1_Bindings()
        {
            InitializeTracking(this);
        }

        ~MainPage_obj1_Bindings()
        {
            ReleaseAllListeners();
        }

        void Connect(int32_t connectionId, IInspectable const& target) override
        {
            switch(connectionId)
            {
            case 14: // MainPage.xaml line 128
                {
                    auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TreeView>();
                    obj14 = targetElement;
                }
                break;
            case 25: // MainPage.xaml line 325
                {
                    auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::TextBlock>();
                    obj25 = targetElement;
                }
                break;
            case 26: // MainPage.xaml line 326
                {
                    auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::TextBlock>();
                    obj26 = targetElement;
                }
                break;
            case 38: // MainPage.xaml line 266
                {
                    auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::GridView>();
                    obj38 = targetElement;
                }
                break;
            case 42: // MainPage.xaml line 228
                {
                    auto targetElement = target.as<::winrt::Windows::UI::Xaml::Controls::TextBlock>();
                    obj42 = targetElement;
                }
                break;
            }
        }

        void DisconnectUnloadedObject(int connectionId) override
        {
            throw ::winrt::hresult_invalid_argument { L"No unloadable elements to disconnect." };
        }


    private:
        // Fields for each control that has bindings.
        ::winrt::Microsoft::UI::Xaml::Controls::TreeView obj14 { nullptr };
        ::winrt::Windows::UI::Xaml::Controls::TextBlock obj25 { nullptr };
        ::winrt::Windows::UI::Xaml::Controls::TextBlock obj26 { nullptr };
        ::winrt::Windows::UI::Xaml::Controls::GridView obj38 { nullptr };
        ::winrt::Windows::UI::Xaml::Controls::TextBlock obj42 { nullptr };

        // Fields for binding tracking.
        ::winrt::weak_ref<::winrt::Windows::UI::Xaml::Data::INotifyPropertyChanged> cachePC_;
        ::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable> cacheVC_TreeViewFolders{nullptr};
        ::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable> cacheVC_ImageSkus{nullptr};
        ::winrt::event_token tokenPC_ {};
        ::winrt::event_token tokenVC_TreeViewFolders {};
        ::winrt::event_token tokenVC_ImageSkus {};

        // Update methods for each path node used in binding steps.

        void Update_(::winrt::SimplePhotoViewer::MainPage obj, int32_t phase)
        {
            _bindingsTracking->UpdatePropertyChangedListener(obj, cachePC_, tokenPC_);
            if (obj)
            {
                if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
                {
                    Update_TreeViewFolders(obj.TreeViewFolders(), phase);
                    Update_CurrentFolderSelectedImageNumber(obj.CurrentFolderSelectedImageNumber(), phase);
                    Update_CurrentFolderImageNumber(obj.CurrentFolderImageNumber(), phase);
                    Update_ImageSkus(obj.ImageSkus(), phase);
                    Update_CurrentSelectedFolder(obj.CurrentSelectedFolder(), phase);
                }
            }
        }

        void Update_TreeViewFolders(::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable> obj, int32_t phase)
        {
            _bindingsTracking->UpdateVectorChangedListener_Object(obj, cacheVC_TreeViewFolders, tokenVC_TreeViewFolders);
            if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
            {
                // MainPage.xaml line 128
                Set_Microsoft_UI_Xaml_Controls_TreeView_ItemsSource(obj14, obj, std::nullopt);
            }
        }

        void Update_CurrentFolderSelectedImageNumber(uint32_t obj, int32_t phase)
        {
            if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
            {
                // MainPage.xaml line 325
                Set_Windows_UI_Xaml_Controls_TextBlock_Text(obj25, ::winrt::to_hstring(obj));
            }
        }

        void Update_CurrentFolderImageNumber(uint32_t obj, int32_t phase)
        {
            if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
            {
                // MainPage.xaml line 326
                Set_Windows_UI_Xaml_Controls_TextBlock_Text(obj26, ::winrt::to_hstring(obj));
            }
        }

        void Update_ImageSkus(::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable> obj, int32_t phase)
        {
            _bindingsTracking->UpdateVectorChangedListener_Object(obj, cacheVC_ImageSkus, tokenVC_ImageSkus);
            if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
            {
                // MainPage.xaml line 266
                Set_Windows_UI_Xaml_Controls_ItemsControl_ItemsSource(obj38, obj, std::nullopt);
            }
        }

        void Update_CurrentSelectedFolder(::winrt::hstring obj, int32_t phase)
        {
            if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
            {
                // MainPage.xaml line 228
                Set_Windows_UI_Xaml_Controls_TextBlock_Text(obj42, obj);
            }
        }

        virtual void ReleaseAllListeners() override
        {
            _bindingsTracking->UpdatePropertyChangedListener(nullptr, cachePC_, tokenPC_);
            _bindingsTracking->UpdateVectorChangedListener_Object(nullptr, cacheVC_TreeViewFolders, tokenVC_TreeViewFolders);
            _bindingsTracking->UpdateVectorChangedListener_Object(nullptr, cacheVC_ImageSkus, tokenVC_ImageSkus);
        }

        virtual void PropertyChanged(IInspectable const& sender, ::winrt::Windows::UI::Xaml::Data::PropertyChangedEventArgs const& e) override
        {
            if (GetDataRoot() && GetDataRoot() == sender)
            {
                auto propName = e.PropertyName();
                auto obj = sender.as<::winrt::SimplePhotoViewer::MainPage>();
                if (propName.empty())
                {
                    if (obj)
                    {
                        Update_TreeViewFolders(obj.TreeViewFolders(), DATA_CHANGED);
                        Update_CurrentFolderSelectedImageNumber(obj.CurrentFolderSelectedImageNumber(), DATA_CHANGED);
                        Update_CurrentFolderImageNumber(obj.CurrentFolderImageNumber(), DATA_CHANGED);
                        Update_ImageSkus(obj.ImageSkus(), DATA_CHANGED);
                        Update_CurrentSelectedFolder(obj.CurrentSelectedFolder(), DATA_CHANGED);
                    }
                }
                else if (propName == L"TreeViewFolders")
                {
                    if (obj)
                    {
                        Update_TreeViewFolders(obj.TreeViewFolders(), DATA_CHANGED);
                    }
                }
                else if (propName == L"CurrentFolderSelectedImageNumber")
                {
                    if (obj)
                    {
                        Update_CurrentFolderSelectedImageNumber(obj.CurrentFolderSelectedImageNumber(), DATA_CHANGED);
                    }
                }
                else if (propName == L"CurrentFolderImageNumber")
                {
                    if (obj)
                    {
                        Update_CurrentFolderImageNumber(obj.CurrentFolderImageNumber(), DATA_CHANGED);
                    }
                }
                else if (propName == L"ImageSkus")
                {
                    if (obj)
                    {
                        Update_ImageSkus(obj.ImageSkus(), DATA_CHANGED);
                    }
                }
                else if (propName == L"CurrentSelectedFolder")
                {
                    if (obj)
                    {
                        Update_CurrentSelectedFolder(obj.CurrentSelectedFolder(), DATA_CHANGED);
                    }
                }
            }
        }

        void CollectionChanged(IInspectable const& sender, ::winrt::Windows::UI::Xaml::Interop::NotifyCollectionChangedEventArgs const& e) override
        {
        }

        void VectorChanged(IInspectable const& sender, ::winrt::Windows::Foundation::Collections::IVectorChangedEventArgs const& e) override
        {
            if (cacheVC_TreeViewFolders && cacheVC_TreeViewFolders == sender)
            {
                ::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable> obj = sender.as<::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable>>();
            }
            if (cacheVC_ImageSkus && cacheVC_ImageSkus == sender)
            {
                ::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable> obj = sender.as<::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable>>();
            }
        }

        void MapChanged(IInspectable const& sender, ::winrt::Windows::Foundation::Collections::IMapChangedEventArgs<::winrt::hstring> const& e) override
        {
        }

        void DependencyPropertyChanged(DependencyObject const& sender, DependencyProperty const& prop) override
        {
            if (sender)
            {
            }
        }


        static void Set_Microsoft_UI_Xaml_Controls_TreeView_ItemsSource(::winrt::Microsoft::UI::Xaml::Controls::TreeView const& obj, ::winrt::Windows::Foundation::IInspectable value, std::optional<::winrt::hstring> const& targetNullValue)
        {
            if (!value && targetNullValue)
            {
                value = ::winrt::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::winrt::xaml_typename<::winrt::Windows::Foundation::IInspectable>(), ::winrt::box_value(::winrt::hstring(targetNullValue.value()))).as<::winrt::Windows::Foundation::IInspectable>();
            }
            obj.ItemsSource(value);
        }

        static void Set_Windows_UI_Xaml_Controls_TextBlock_Text(::winrt::Windows::UI::Xaml::Controls::TextBlock const& obj, ::winrt::hstring const& value)
        {
            obj.Text(value);
        }

        static void Set_Windows_UI_Xaml_Controls_ItemsControl_ItemsSource(::winrt::Windows::UI::Xaml::Controls::ItemsControl const& obj, ::winrt::Windows::Foundation::IInspectable value, std::optional<::winrt::hstring> const& targetNullValue)
        {
            if (!value && targetNullValue)
            {
                value = ::winrt::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::winrt::xaml_typename<::winrt::Windows::Foundation::IInspectable>(), ::winrt::box_value(::winrt::hstring(targetNullValue.value()))).as<::winrt::Windows::Foundation::IInspectable>();
            }
            obj.ItemsSource(value);
        }
    }; 

    template struct MainPageT<struct MainPage>;
}


#pragma warning(pop)


