//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "pch.h"
#include <memory>

#include "XamlTypeInfo.xaml.g.h"

#include "DetailPage.h"
#include "App.h"
#include "MainPage.h"
#include "XamlBindingInfo.xaml.g.hpp"
#include "DetailPage.xaml.g.hpp"
#include "App.xaml.g.hpp"
#include "MainPage.xaml.g.hpp"

namespace winrt::SimplePhotoViewer::implementation
{
using IXamlMember = ::winrt::Windows::UI::Xaml::Markup::IXamlMember;
using IXamlType = ::winrt::Windows::UI::Xaml::Markup::IXamlType;
using TypeKind = ::winrt::Windows::UI::Xaml::Interop::TypeKind;

template <typename T>
::winrt::Windows::Foundation::IInspectable ActivateType()
{
    return T();
}

template <typename T>
::winrt::Windows::Foundation::IInspectable ActivateLocalType()
{
    return ::winrt::make<T>();
}

template<typename TInstance, typename TItem>
void CollectionAdd(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& item)
{
    instance.as<TInstance>().Append(::winrt::unbox_value<TItem>(item));
}

template<typename TInstance, typename TKey, typename TItem>
void DictionaryAdd(
    ::winrt::Windows::Foundation::IInspectable const& instance,
    ::winrt::Windows::Foundation::IInspectable const& key,
    ::winrt::Windows::Foundation::IInspectable const& item)
{
    instance.as<TInstance>().Insert(::winrt::unbox_value<TKey>(key), ::winrt::unbox_value<TItem>(item));
}

template<typename T>
::winrt::Windows::Foundation::IInspectable FromStringConverter(
    XamlUserType const& userType, 
    ::winrt::hstring const& input)
{
    return ::winrt::box_value(static_cast<T>(userType.CreateEnumUIntFromString(input)));
}

template<typename TDeclaringType, typename TValue>
::winrt::Windows::Foundation::IInspectable GetValueTypeMember_IsExpanded(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value<TValue>(instance.as<TDeclaringType>().IsExpanded());
}

template<typename TDeclaringType, typename TValue>
::winrt::Windows::Foundation::IInspectable GetValueTypeMember_HasUnrealizedChildren(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value<TValue>(instance.as<TDeclaringType>().HasUnrealizedChildren());
}

template<typename TDeclaringType, typename TValue>
::winrt::Windows::Foundation::IInspectable GetValueTypeMember_GlyphSize(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value<TValue>(instance.as<TDeclaringType>().GlyphSize());
}

template<typename TDeclaringType, typename TValue>
::winrt::Windows::Foundation::IInspectable GetValueTypeMember_GlyphOpacity(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value<TValue>(instance.as<TDeclaringType>().GlyphOpacity());
}

template<typename TDeclaringType, typename TValue>
::winrt::Windows::Foundation::IInspectable GetValueTypeMember_CanDragItems(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value<TValue>(instance.as<TDeclaringType>().CanDragItems());
}

template<typename TDeclaringType, typename TValue>
::winrt::Windows::Foundation::IInspectable GetValueTypeMember_CanReorderItems(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value<TValue>(instance.as<TDeclaringType>().CanReorderItems());
}

template<typename TDeclaringType, typename TValue>
::winrt::Windows::Foundation::IInspectable GetValueTypeMember_SelectionMode(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value<TValue>(instance.as<TDeclaringType>().SelectionMode());
}

template<typename TDeclaringType, typename TValue>
::winrt::Windows::Foundation::IInspectable GetValueTypeMember_Depth(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value<TValue>(instance.as<TDeclaringType>().Depth());
}

template<typename TDeclaringType, typename TValue>
::winrt::Windows::Foundation::IInspectable GetValueTypeMember_HasChildren(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value<TValue>(instance.as<TDeclaringType>().HasChildren());
}

template<typename TDeclaringType, typename TValue>
::winrt::Windows::Foundation::IInspectable GetValueTypeMember_CurrentFolderImageNumber(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value<TValue>(instance.as<TDeclaringType>().CurrentFolderImageNumber());
}

template<typename TDeclaringType, typename TValue>
::winrt::Windows::Foundation::IInspectable GetValueTypeMember_CurrentFolderSelectedImageNumber(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value<TValue>(instance.as<TDeclaringType>().CurrentFolderSelectedImageNumber());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_ExpandedGlyph(::winrt::Windows::Foundation::IInspectable const& instance)
{
   return ::winrt::box_value(::winrt::Windows::Foundation::PropertyValue::CreateString(instance.as<T>().ExpandedGlyph()));
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_CollapsedGlyph(::winrt::Windows::Foundation::IInspectable const& instance)
{
   return ::winrt::box_value(::winrt::Windows::Foundation::PropertyValue::CreateString(instance.as<T>().CollapsedGlyph()));
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_CurrentSelectedFolder(::winrt::Windows::Foundation::IInspectable const& instance)
{
   return ::winrt::box_value(::winrt::Windows::Foundation::PropertyValue::CreateString(instance.as<T>().CurrentSelectedFolder()));
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_SelectedItem(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().SelectedItem());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_ImageSkus(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().ImageSkus());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_FolderTemplate(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().FolderTemplate());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_FileTemplate(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().FileTemplate());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_ItemsSource(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().ItemsSource());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_GlyphBrush(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().GlyphBrush());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_TreeViewItemTemplateSettings(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().TreeViewItemTemplateSettings());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_ItemTemplateSelector(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().ItemTemplateSelector());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_ItemTemplate(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().ItemTemplate());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_ItemContainerTransitions(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().ItemContainerTransitions());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_ItemContainerStyleSelector(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().ItemContainerStyleSelector());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_ItemContainerStyle(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().ItemContainerStyle());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_RootNodes(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().RootNodes());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_Content(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().Content());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_Children(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().Children());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_Parent(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().Parent());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_SelectedNodes(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().SelectedNodes());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_BufferImageSkus(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().BufferImageSkus());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_SearchResults(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().SearchResults());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_TreeViewFolders(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().TreeViewFolders());
}

template<typename TDeclaringType, typename TValue>
void SetEnumMember_SelectionMode(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().SelectionMode(::winrt::unbox_value<TValue>(value));
}

template<typename TDeclaringType, typename TValue>
void SetValueTypeMember_IsExpanded(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().IsExpanded(::winrt::unbox_value<TValue>(value));
}

template<typename TDeclaringType, typename TValue>
void SetValueTypeMember_HasUnrealizedChildren(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().HasUnrealizedChildren(::winrt::unbox_value<TValue>(value));
}

template<typename TDeclaringType, typename TValue>
void SetValueTypeMember_GlyphSize(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().GlyphSize(::winrt::unbox_value<TValue>(value));
}

template<typename TDeclaringType, typename TValue>
void SetValueTypeMember_GlyphOpacity(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().GlyphOpacity(::winrt::unbox_value<TValue>(value));
}

template<typename TDeclaringType, typename TValue>
void SetValueTypeMember_CanDragItems(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().CanDragItems(::winrt::unbox_value<TValue>(value));
}

template<typename TDeclaringType, typename TValue>
void SetValueTypeMember_CanReorderItems(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().CanReorderItems(::winrt::unbox_value<TValue>(value));
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_ExpandedGlyph(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    return instance.as<TDeclaringType>().ExpandedGlyph(::winrt::unbox_value<::winrt::hstring>(value));
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_CollapsedGlyph(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    return instance.as<TDeclaringType>().CollapsedGlyph(::winrt::unbox_value<::winrt::hstring>(value));
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_CurrentSelectedFolder(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    return instance.as<TDeclaringType>().CurrentSelectedFolder(::winrt::unbox_value<::winrt::hstring>(value));
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_SelectedItem(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().SelectedItem(value.as<TValue>());
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_FolderTemplate(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().FolderTemplate(value.as<TValue>());
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_FileTemplate(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().FileTemplate(value.as<TValue>());
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_ItemsSource(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().ItemsSource(value.as<TValue>());
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_GlyphBrush(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().GlyphBrush(value.as<TValue>());
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_ItemTemplateSelector(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().ItemTemplateSelector(value.as<TValue>());
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_ItemTemplate(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().ItemTemplate(value.as<TValue>());
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_ItemContainerTransitions(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().ItemContainerTransitions(value.as<TValue>());
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_ItemContainerStyleSelector(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().ItemContainerStyleSelector(value.as<TValue>());
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_ItemContainerStyle(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().ItemContainerStyle(value.as<TValue>());
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_Content(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().Content(value.as<TValue>());
}

enum TypeInfo_Flags
{
    TypeInfo_Flags_None                 = 0x00,
    TypeInfo_Flags_IsLocalType          = 0x01,
    TypeInfo_Flags_IsSystemType         = 0x02,
    TypeInfo_Flags_IsReturnTypeStub     = 0x04,
    TypeInfo_Flags_IsBindable           = 0x08,
    TypeInfo_Flags_IsMarkupExtension    = 0x10, 
};

struct TypeInfo
{
    PCWSTR  typeName;
    PCWSTR contentPropertyName;
    ::winrt::Windows::Foundation::IInspectable (*activator)();
    void (*collectionAdd)(::winrt::Windows::Foundation::IInspectable const&, ::winrt::Windows::Foundation::IInspectable const&);
    void (*dictionaryAdd)(::winrt::Windows::Foundation::IInspectable const&, ::winrt::Windows::Foundation::IInspectable const&, ::winrt::Windows::Foundation::IInspectable const&);
    ::winrt::Windows::Foundation::IInspectable (*fromStringConverter)(XamlUserType const&, ::winrt::hstring const& );
    int     baseTypeIndex;
    int     firstMemberIndex;
    int     firstEnumValueIndex;
    int     createFromStringIndex;
    TypeKind kindOfType;
    unsigned int flags;
    int boxedTypeIndex;
};


const TypeInfo TypeInfos[] = 
{
    //   0
    L"Int32", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //   1
    L"Object", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //   2
    L"Double", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //   3
    L"String", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //   4
    L"UInt32", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //   5
    L"Boolean", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //   6
    L"System.Enum", L"",
    nullptr, nullptr, nullptr, nullptr,
    7, // System.ValueType
    0, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_None,
    -1,
    //   7
    L"System.ValueType", L"",
    nullptr, nullptr, nullptr, nullptr,
    1, // Object
    0, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_None,
    -1,
    //   8
    L"Windows.UI.Xaml.Style", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //   9
    L"SimplePhotoViewer.ImageSku", L"",
    nullptr, nullptr, nullptr, nullptr,
    1, // Object
    0, 0, -1, TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_IsReturnTypeStub | TypeInfo_Flags_None,
    -1,
    //  10
    L"SimplePhotoViewer.MainPage", L"",
    &ActivateLocalType<::winrt::SimplePhotoViewer::implementation::MainPage>, nullptr, nullptr, nullptr,
    14, // Windows.UI.Xaml.Controls.Page
    0, 0, -1, TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    -1,
    //  11
    L"Windows.UI.Xaml.Media.Brush", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    7, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  12
    L"SimplePhotoViewer.DetailPage", L"",
    &ActivateLocalType<::winrt::SimplePhotoViewer::implementation::DetailPage>, nullptr, nullptr, nullptr,
    14, // Windows.UI.Xaml.Controls.Page
    7, 0, -1, TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    -1,
    //  13
    L"Windows.UI.Xaml.DataTemplate", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    9, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  14
    L"Windows.UI.Xaml.Controls.Page", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    9, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  15
    L"Windows.UI.Xaml.DependencyObject", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    9, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  16
    L"Windows.UI.Xaml.Controls.Control", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    9, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  17
    L"Windows.UI.Xaml.ResourceDictionary", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    9, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  18
    L"Microsoft.UI.Xaml.Controls.TreeView", L"",
    &ActivateType<::winrt::Microsoft::UI::Xaml::Controls::TreeView>, nullptr, nullptr, nullptr,
    16, // Windows.UI.Xaml.Controls.Control
    9, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_None,
    -1,
    //  19
    L"Windows.UI.Xaml.Controls.UserControl", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    20, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  20
    L"Windows.UI.Xaml.Controls.ListViewItem", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    20, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  21
    L"Windows.UI.Xaml.Controls.StyleSelector", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    20, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  22
    L"Microsoft.UI.Xaml.Controls.TreeViewItem", L"",
    &ActivateType<::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem>, nullptr, nullptr, nullptr,
    20, // Windows.UI.Xaml.Controls.ListViewItem
    20, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_None,
    -1,
    //  23
    L"Windows.UI.Xaml.Controls.ContentControl", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    29, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  24
    L"Microsoft.UI.Xaml.Controls.TreeViewNode", L"",
    &ActivateType<::winrt::Microsoft::UI::Xaml::Controls::TreeViewNode>, nullptr, nullptr, nullptr,
    15, // Windows.UI.Xaml.DependencyObject
    29, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsBindable | TypeInfo_Flags_None,
    -1,
    //  25
    L"Windows.UI.Xaml.Controls.DataTemplateSelector", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    36, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  26
    L"SimplePhotoViewer.ExplorerItemTemplateSelector", L"",
    &ActivateLocalType<::winrt::SimplePhotoViewer::implementation::ExplorerItemTemplateSelector>, nullptr, nullptr, nullptr,
    25, // Windows.UI.Xaml.Controls.DataTemplateSelector
    36, 0, -1, TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    -1,
    //  27
    L"Microsoft.UI.Xaml.Controls.XamlControlsResources", L"",
    &ActivateType<::winrt::Microsoft::UI::Xaml::Controls::XamlControlsResources>, nullptr, &DictionaryAdd<::winrt::Microsoft::UI::Xaml::Controls::XamlControlsResources, ::winrt::Windows::Foundation::IInspectable, ::winrt::Windows::Foundation::IInspectable>, nullptr,
    17, // Windows.UI.Xaml.ResourceDictionary
    38, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_None,
    -1,
    //  28
    L"Microsoft.UI.Xaml.Controls.TreeViewSelectionMode", L"",
    nullptr, nullptr, nullptr, &FromStringConverter<::winrt::Microsoft::UI::Xaml::Controls::TreeViewSelectionMode>,
    6, // System.Enum
    38, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_None,
    -1,
    //  29
    L"Windows.UI.Xaml.Media.Animation.TransitionCollection", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    38, 3, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  30
    L"Microsoft.UI.Xaml.Controls.TreeViewItemTemplateSettings", L"",
    nullptr, nullptr, nullptr, nullptr,
    15, // Windows.UI.Xaml.DependencyObject
    38, 3, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsReturnTypeStub | TypeInfo_Flags_None,
    -1,
    //  31
    L"Windows.Foundation.Collections.IObservableVector`1<Object>", L"",
    nullptr, &CollectionAdd<::winrt::Windows::Foundation::Collections::IObservableVector<::winrt::Windows::Foundation::IInspectable>, ::winrt::Windows::Foundation::IInspectable>, nullptr, nullptr,
    -1,
    38, 3, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsReturnTypeStub | TypeInfo_Flags_None,
    -1,
    //  32
    L"Windows.Foundation.Collections.IVector`1<Microsoft.UI.Xaml.Controls.TreeViewNode>", L"",
    nullptr, &CollectionAdd<::winrt::Windows::Foundation::Collections::IVector<::winrt::Microsoft::UI::Xaml::Controls::TreeViewNode>, ::winrt::Microsoft::UI::Xaml::Controls::TreeViewNode>, nullptr, nullptr,
    -1,
    38, 3, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsReturnTypeStub | TypeInfo_Flags_None,
    -1,
    //  Last type here is for padding
    L"", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1, 
    38, 3, -1, TypeKind::Custom,
    TypeInfo_Flags_None,
};

constexpr UINT TypeInfoLookup[] = { 
      0,   //   0
      0,   //   1
      0,   //   2
      0,   //   3
      0,   //   4
      0,   //   5
      1,   //   6
      5,   //   7
      6,   //   8
      6,   //   9
      6,   //  10
      6,   //  11
      7,   //  12
      7,   //  13
      7,   //  14
      7,   //  15
      7,   //  16
      8,   //  17
      8,   //  18
      8,   //  19
      8,   //  20
      8,   //  21
      9,   //  22
      9,   //  23
      9,   //  24
      9,   //  25
      9,   //  26
     11,   //  27
     12,   //  28
     14,   //  29
     15,   //  30
     15,   //  31
     15,   //  32
     17,   //  33
     17,   //  34
     18,   //  35
     19,   //  36
     20,   //  37
     21,   //  38
     22,   //  39
     25,   //  40
     25,   //  41
     25,   //  42
     25,   //  43
     25,   //  44
     25,   //  45
     26,   //  46
     27,   //  47
     27,   //  48
     29,   //  49
     29,   //  50
     29,   //  51
     29,   //  52
     30,   //  53
     30,   //  54
     30,   //  55
     31,   //  56
     31,   //  57
     31,   //  58
     32,   //  59
     32,   //  60
     32,   //  61
     32,   //  62
     32,   //  63
     32,   //  64
     32,   //  65
     32,   //  66
     32,   //  67
     32,   //  68
     32,   //  69
     32,   //  70
     32,   //  71
     32,   //  72
     32,   //  73
     32,   //  74
     32,   //  75
     32,   //  76
     32,   //  77
     32,   //  78
     32,   //  79
     32,   //  80
     32,   //  81
     33,   //  82
};

struct EnumValueInfo
{
    PCWSTR name;
    int eValue;
};

const EnumValueInfo EnumValues[] =
{ 
    L"None", static_cast<int>(::winrt::Microsoft::UI::Xaml::Controls::TreeViewSelectionMode::None),
    L"Single", static_cast<int>(::winrt::Microsoft::UI::Xaml::Controls::TreeViewSelectionMode::Single),
    L"Multiple", static_cast<int>(::winrt::Microsoft::UI::Xaml::Controls::TreeViewSelectionMode::Multiple),
};

struct MemberInfo 
{
    PCWSTR shortName;
    ::winrt::Windows::Foundation::IInspectable (*getter)(::winrt::Windows::Foundation::IInspectable const&);
    void (*setter)(::winrt::Windows::Foundation::IInspectable const&, ::winrt::Windows::Foundation::IInspectable const&);
    int typeIndex;
    int targetTypeIndex;
    bool isReadOnly;
    bool isDependencyProperty;
    bool isAttachable;
};

const MemberInfo MemberInfos[] = 
{
    //   0 - SimplePhotoViewer.MainPage.CurrentSelectedFolder
    L"CurrentSelectedFolder",
    &GetReferenceTypeMember_CurrentSelectedFolder<::winrt::SimplePhotoViewer::MainPage>,
    &SetReferenceTypeMember_CurrentSelectedFolder<::winrt::SimplePhotoViewer::MainPage, ::winrt::hstring>,
    3, // String
    -1,
    false, false, false,
    //   1 - SimplePhotoViewer.MainPage.BufferImageSkus
    L"BufferImageSkus",
    &GetReferenceTypeMember_BufferImageSkus<::winrt::SimplePhotoViewer::MainPage>,
    nullptr,
    31, // Windows.Foundation.Collections.IObservableVector`1<Object>
    -1,
    true,  false, false,
    //   2 - SimplePhotoViewer.MainPage.CurrentFolderImageNumber
    L"CurrentFolderImageNumber",
    &GetValueTypeMember_CurrentFolderImageNumber<::winrt::SimplePhotoViewer::MainPage, uint32_t>,
    nullptr,
    4, // UInt32
    -1,
    true,  false, false,
    //   3 - SimplePhotoViewer.MainPage.CurrentFolderSelectedImageNumber
    L"CurrentFolderSelectedImageNumber",
    &GetValueTypeMember_CurrentFolderSelectedImageNumber<::winrt::SimplePhotoViewer::MainPage, uint32_t>,
    nullptr,
    4, // UInt32
    -1,
    true,  false, false,
    //   4 - SimplePhotoViewer.MainPage.ImageSkus
    L"ImageSkus",
    &GetReferenceTypeMember_ImageSkus<::winrt::SimplePhotoViewer::MainPage>,
    nullptr,
    31, // Windows.Foundation.Collections.IObservableVector`1<Object>
    -1,
    true,  false, false,
    //   5 - SimplePhotoViewer.MainPage.SearchResults
    L"SearchResults",
    &GetReferenceTypeMember_SearchResults<::winrt::SimplePhotoViewer::MainPage>,
    nullptr,
    31, // Windows.Foundation.Collections.IObservableVector`1<Object>
    -1,
    true,  false, false,
    //   6 - SimplePhotoViewer.MainPage.TreeViewFolders
    L"TreeViewFolders",
    &GetReferenceTypeMember_TreeViewFolders<::winrt::SimplePhotoViewer::MainPage>,
    nullptr,
    31, // Windows.Foundation.Collections.IObservableVector`1<Object>
    -1,
    true,  false, false,
    //   7 - SimplePhotoViewer.DetailPage.SelectedItem
    L"SelectedItem",
    &GetReferenceTypeMember_SelectedItem<::winrt::SimplePhotoViewer::DetailPage>,
    &SetReferenceTypeMember_SelectedItem<::winrt::SimplePhotoViewer::DetailPage, ::winrt::SimplePhotoViewer::ImageSku>,
    9, // SimplePhotoViewer.ImageSku
    -1,
    false, false, false,
    //   8 - SimplePhotoViewer.DetailPage.ImageSkus
    L"ImageSkus",
    &GetReferenceTypeMember_ImageSkus<::winrt::SimplePhotoViewer::DetailPage>,
    nullptr,
    31, // Windows.Foundation.Collections.IObservableVector`1<Object>
    -1,
    true,  false, false,
    //   9 - Microsoft.UI.Xaml.Controls.TreeView.ItemsSource
    L"ItemsSource",
    &GetReferenceTypeMember_ItemsSource<::winrt::Microsoft::UI::Xaml::Controls::TreeView>,
    &SetReferenceTypeMember_ItemsSource<::winrt::Microsoft::UI::Xaml::Controls::TreeView, ::winrt::Windows::Foundation::IInspectable>,
    1, // Object
    -1,
    false, true,  false,
    //  10 - Microsoft.UI.Xaml.Controls.TreeView.CanDragItems
    L"CanDragItems",
    &GetValueTypeMember_CanDragItems<::winrt::Microsoft::UI::Xaml::Controls::TreeView, bool>,
    &SetValueTypeMember_CanDragItems<::winrt::Microsoft::UI::Xaml::Controls::TreeView, bool>,
    5, // Boolean
    -1,
    false, true,  false,
    //  11 - Microsoft.UI.Xaml.Controls.TreeView.CanReorderItems
    L"CanReorderItems",
    &GetValueTypeMember_CanReorderItems<::winrt::Microsoft::UI::Xaml::Controls::TreeView, bool>,
    &SetValueTypeMember_CanReorderItems<::winrt::Microsoft::UI::Xaml::Controls::TreeView, bool>,
    5, // Boolean
    -1,
    false, true,  false,
    //  12 - Microsoft.UI.Xaml.Controls.TreeView.ItemTemplateSelector
    L"ItemTemplateSelector",
    &GetReferenceTypeMember_ItemTemplateSelector<::winrt::Microsoft::UI::Xaml::Controls::TreeView>,
    &SetReferenceTypeMember_ItemTemplateSelector<::winrt::Microsoft::UI::Xaml::Controls::TreeView, ::winrt::Windows::UI::Xaml::Controls::DataTemplateSelector>,
    25, // Windows.UI.Xaml.Controls.DataTemplateSelector
    -1,
    false, true,  false,
    //  13 - Microsoft.UI.Xaml.Controls.TreeView.SelectionMode
    L"SelectionMode",
    &GetValueTypeMember_SelectionMode<::winrt::Microsoft::UI::Xaml::Controls::TreeView, ::winrt::Microsoft::UI::Xaml::Controls::TreeViewSelectionMode>,
    &SetEnumMember_SelectionMode<::winrt::Microsoft::UI::Xaml::Controls::TreeView, ::winrt::Microsoft::UI::Xaml::Controls::TreeViewSelectionMode>,
    28, // Microsoft.UI.Xaml.Controls.TreeViewSelectionMode
    -1,
    false, true,  false,
    //  14 - Microsoft.UI.Xaml.Controls.TreeView.ItemTemplate
    L"ItemTemplate",
    &GetReferenceTypeMember_ItemTemplate<::winrt::Microsoft::UI::Xaml::Controls::TreeView>,
    &SetReferenceTypeMember_ItemTemplate<::winrt::Microsoft::UI::Xaml::Controls::TreeView, ::winrt::Windows::UI::Xaml::DataTemplate>,
    13, // Windows.UI.Xaml.DataTemplate
    -1,
    false, true,  false,
    //  15 - Microsoft.UI.Xaml.Controls.TreeView.ItemContainerTransitions
    L"ItemContainerTransitions",
    &GetReferenceTypeMember_ItemContainerTransitions<::winrt::Microsoft::UI::Xaml::Controls::TreeView>,
    &SetReferenceTypeMember_ItemContainerTransitions<::winrt::Microsoft::UI::Xaml::Controls::TreeView, ::winrt::Windows::UI::Xaml::Media::Animation::TransitionCollection>,
    29, // Windows.UI.Xaml.Media.Animation.TransitionCollection
    -1,
    false, true,  false,
    //  16 - Microsoft.UI.Xaml.Controls.TreeView.ItemContainerStyleSelector
    L"ItemContainerStyleSelector",
    &GetReferenceTypeMember_ItemContainerStyleSelector<::winrt::Microsoft::UI::Xaml::Controls::TreeView>,
    &SetReferenceTypeMember_ItemContainerStyleSelector<::winrt::Microsoft::UI::Xaml::Controls::TreeView, ::winrt::Windows::UI::Xaml::Controls::StyleSelector>,
    21, // Windows.UI.Xaml.Controls.StyleSelector
    -1,
    false, true,  false,
    //  17 - Microsoft.UI.Xaml.Controls.TreeView.ItemContainerStyle
    L"ItemContainerStyle",
    &GetReferenceTypeMember_ItemContainerStyle<::winrt::Microsoft::UI::Xaml::Controls::TreeView>,
    &SetReferenceTypeMember_ItemContainerStyle<::winrt::Microsoft::UI::Xaml::Controls::TreeView, ::winrt::Windows::UI::Xaml::Style>,
    8, // Windows.UI.Xaml.Style
    -1,
    false, true,  false,
    //  18 - Microsoft.UI.Xaml.Controls.TreeView.RootNodes
    L"RootNodes",
    &GetReferenceTypeMember_RootNodes<::winrt::Microsoft::UI::Xaml::Controls::TreeView>,
    nullptr,
    32, // Windows.Foundation.Collections.IVector`1<Microsoft.UI.Xaml.Controls.TreeViewNode>
    -1,
    true,  false, false,
    //  19 - Microsoft.UI.Xaml.Controls.TreeView.SelectedNodes
    L"SelectedNodes",
    &GetReferenceTypeMember_SelectedNodes<::winrt::Microsoft::UI::Xaml::Controls::TreeView>,
    nullptr,
    32, // Windows.Foundation.Collections.IVector`1<Microsoft.UI.Xaml.Controls.TreeViewNode>
    -1,
    true,  false, false,
    //  20 - Microsoft.UI.Xaml.Controls.TreeViewItem.ItemsSource
    L"ItemsSource",
    &GetReferenceTypeMember_ItemsSource<::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem>,
    &SetReferenceTypeMember_ItemsSource<::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem, ::winrt::Windows::Foundation::IInspectable>,
    1, // Object
    -1,
    false, true,  false,
    //  21 - Microsoft.UI.Xaml.Controls.TreeViewItem.IsExpanded
    L"IsExpanded",
    &GetValueTypeMember_IsExpanded<::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem, bool>,
    &SetValueTypeMember_IsExpanded<::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem, bool>,
    5, // Boolean
    -1,
    false, true,  false,
    //  22 - Microsoft.UI.Xaml.Controls.TreeViewItem.HasUnrealizedChildren
    L"HasUnrealizedChildren",
    &GetValueTypeMember_HasUnrealizedChildren<::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem, bool>,
    &SetValueTypeMember_HasUnrealizedChildren<::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem, bool>,
    5, // Boolean
    -1,
    false, true,  false,
    //  23 - Microsoft.UI.Xaml.Controls.TreeViewItem.GlyphSize
    L"GlyphSize",
    &GetValueTypeMember_GlyphSize<::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem, double>,
    &SetValueTypeMember_GlyphSize<::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem, double>,
    2, // Double
    -1,
    false, true,  false,
    //  24 - Microsoft.UI.Xaml.Controls.TreeViewItem.GlyphOpacity
    L"GlyphOpacity",
    &GetValueTypeMember_GlyphOpacity<::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem, double>,
    &SetValueTypeMember_GlyphOpacity<::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem, double>,
    2, // Double
    -1,
    false, true,  false,
    //  25 - Microsoft.UI.Xaml.Controls.TreeViewItem.GlyphBrush
    L"GlyphBrush",
    &GetReferenceTypeMember_GlyphBrush<::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem>,
    &SetReferenceTypeMember_GlyphBrush<::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem, ::winrt::Windows::UI::Xaml::Media::Brush>,
    11, // Windows.UI.Xaml.Media.Brush
    -1,
    false, true,  false,
    //  26 - Microsoft.UI.Xaml.Controls.TreeViewItem.ExpandedGlyph
    L"ExpandedGlyph",
    &GetReferenceTypeMember_ExpandedGlyph<::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem>,
    &SetReferenceTypeMember_ExpandedGlyph<::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem, ::winrt::hstring>,
    3, // String
    -1,
    false, true,  false,
    //  27 - Microsoft.UI.Xaml.Controls.TreeViewItem.CollapsedGlyph
    L"CollapsedGlyph",
    &GetReferenceTypeMember_CollapsedGlyph<::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem>,
    &SetReferenceTypeMember_CollapsedGlyph<::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem, ::winrt::hstring>,
    3, // String
    -1,
    false, true,  false,
    //  28 - Microsoft.UI.Xaml.Controls.TreeViewItem.TreeViewItemTemplateSettings
    L"TreeViewItemTemplateSettings",
    &GetReferenceTypeMember_TreeViewItemTemplateSettings<::winrt::Microsoft::UI::Xaml::Controls::TreeViewItem>,
    nullptr,
    30, // Microsoft.UI.Xaml.Controls.TreeViewItemTemplateSettings
    -1,
    true,  true,  false,
    //  29 - Microsoft.UI.Xaml.Controls.TreeViewNode.IsExpanded
    L"IsExpanded",
    &GetValueTypeMember_IsExpanded<::winrt::Microsoft::UI::Xaml::Controls::TreeViewNode, bool>,
    &SetValueTypeMember_IsExpanded<::winrt::Microsoft::UI::Xaml::Controls::TreeViewNode, bool>,
    5, // Boolean
    -1,
    false, true,  false,
    //  30 - Microsoft.UI.Xaml.Controls.TreeViewNode.HasUnrealizedChildren
    L"HasUnrealizedChildren",
    &GetValueTypeMember_HasUnrealizedChildren<::winrt::Microsoft::UI::Xaml::Controls::TreeViewNode, bool>,
    &SetValueTypeMember_HasUnrealizedChildren<::winrt::Microsoft::UI::Xaml::Controls::TreeViewNode, bool>,
    5, // Boolean
    -1,
    false, false, false,
    //  31 - Microsoft.UI.Xaml.Controls.TreeViewNode.Content
    L"Content",
    &GetReferenceTypeMember_Content<::winrt::Microsoft::UI::Xaml::Controls::TreeViewNode>,
    &SetReferenceTypeMember_Content<::winrt::Microsoft::UI::Xaml::Controls::TreeViewNode, ::winrt::Windows::Foundation::IInspectable>,
    1, // Object
    -1,
    false, true,  false,
    //  32 - Microsoft.UI.Xaml.Controls.TreeViewNode.Children
    L"Children",
    &GetReferenceTypeMember_Children<::winrt::Microsoft::UI::Xaml::Controls::TreeViewNode>,
    nullptr,
    32, // Windows.Foundation.Collections.IVector`1<Microsoft.UI.Xaml.Controls.TreeViewNode>
    -1,
    true,  false, false,
    //  33 - Microsoft.UI.Xaml.Controls.TreeViewNode.Depth
    L"Depth",
    &GetValueTypeMember_Depth<::winrt::Microsoft::UI::Xaml::Controls::TreeViewNode, int32_t>,
    nullptr,
    0, // Int32
    -1,
    true,  true,  false,
    //  34 - Microsoft.UI.Xaml.Controls.TreeViewNode.HasChildren
    L"HasChildren",
    &GetValueTypeMember_HasChildren<::winrt::Microsoft::UI::Xaml::Controls::TreeViewNode, bool>,
    nullptr,
    5, // Boolean
    -1,
    true,  true,  false,
    //  35 - Microsoft.UI.Xaml.Controls.TreeViewNode.Parent
    L"Parent",
    &GetReferenceTypeMember_Parent<::winrt::Microsoft::UI::Xaml::Controls::TreeViewNode>,
    nullptr,
    24, // Microsoft.UI.Xaml.Controls.TreeViewNode
    -1,
    true,  false, false,
    //  36 - SimplePhotoViewer.ExplorerItemTemplateSelector.FolderTemplate
    L"FolderTemplate",
    &GetReferenceTypeMember_FolderTemplate<::winrt::SimplePhotoViewer::ExplorerItemTemplateSelector>,
    &SetReferenceTypeMember_FolderTemplate<::winrt::SimplePhotoViewer::ExplorerItemTemplateSelector, ::winrt::Windows::UI::Xaml::DataTemplate>,
    13, // Windows.UI.Xaml.DataTemplate
    -1,
    false, false, false,
    //  37 - SimplePhotoViewer.ExplorerItemTemplateSelector.FileTemplate
    L"FileTemplate",
    &GetReferenceTypeMember_FileTemplate<::winrt::SimplePhotoViewer::ExplorerItemTemplateSelector>,
    &SetReferenceTypeMember_FileTemplate<::winrt::SimplePhotoViewer::ExplorerItemTemplateSelector, ::winrt::Windows::UI::Xaml::DataTemplate>,
    13, // Windows.UI.Xaml.DataTemplate
    -1,
    false, false, false,
};

PCWSTR GetShortName(PCWSTR longName)
{
    PCWSTR separator = wcsrchr(longName, '.');
    return separator ? separator + 1: longName;
}

const TypeInfo* GetTypeInfo(::winrt::hstring const& typeName)
{
    size_t typeNameLength = typeName.size();
    if (typeNameLength < _countof(TypeInfoLookup) - 1)
    {
        const auto begin = TypeInfos + TypeInfoLookup[typeNameLength];
        const auto end = TypeInfos + TypeInfoLookup[typeNameLength + 1];
        auto pos = std::find_if(begin, end, [&typeName](TypeInfo const& elem)
        {
            return wcscmp(typeName.data(), elem.typeName) == 0;
        });
        if (pos != end)
        {
            return pos;
        }
    }
    return nullptr;
}

const MemberInfo* GetMemberInfo(::winrt::hstring const& longMemberName)
{
    const auto dotPosition = std::find(longMemberName.crbegin(), longMemberName.crend(), L'.').base();
    if (dotPosition != longMemberName.end())
    {
        const auto sizeBeforeDot = static_cast<::winrt::hstring::size_type>(dotPosition - longMemberName.begin()) - 1;
        const TypeInfo* pTypeInfo = GetTypeInfo(::winrt::hstring{longMemberName.data(), sizeBeforeDot});
        if (pTypeInfo)
        {
            const TypeInfo* pNextTypeInfo = pTypeInfo + 1;
            PCWSTR shortMemberName = GetShortName(longMemberName.data());
            const auto begin = MemberInfos + pTypeInfo->firstMemberIndex;
            const auto end = MemberInfos + pNextTypeInfo->firstMemberIndex;
            auto info = std::find_if(begin, end,
                [shortMemberName](const MemberInfo& elem)
            {
                return wcscmp(shortMemberName, elem.shortName) == 0;
            });
            if (info != end)
            {
                return info;
            }
        }
    }
    return nullptr;
}

std::vector<::winrt::Windows::UI::Xaml::Markup::IXamlMetadataProvider> const& XamlTypeInfoProvider::OtherProviders()
{
    if (_otherProviders.empty())
    {
        _otherProviders.push_back(::winrt::Microsoft::UI::Xaml::XamlTypeInfo::XamlControlsXamlMetaDataProvider());
        _otherProviders.push_back(::winrt::Microsoft::UI::Xaml::XamlTypeInfo::XamlControlsXamlMetaDataProvider());
    }
    return _otherProviders;
}

IXamlType XamlTypeInfoProvider::CreateXamlType(::winrt::hstring const& typeName)
{
    const TypeInfo* pTypeInfo = GetTypeInfo(typeName);
    const TypeInfo* pNextTypeInfo = pTypeInfo + 1;
    if (!pTypeInfo || !pNextTypeInfo)
    {
        return nullptr;
    }
    else if (pTypeInfo->flags & TypeInfo_Flags_IsSystemType)
    {
        return ::winrt::make<XamlSystemBaseType>(typeName);
    }
    else
    {
        ::winrt::hstring baseName { pTypeInfo->baseTypeIndex >= 0 ? TypeInfos[pTypeInfo->baseTypeIndex].typeName : L""};
        ::winrt::hstring boxedName { pTypeInfo->boxedTypeIndex >= 0 ? TypeInfos[pTypeInfo->boxedTypeIndex].typeName : L""};
        auto userType = ::winrt::make_self<XamlUserType>(shared_from_this(), pTypeInfo->typeName, GetXamlTypeByName(baseName));
        userType->_kindOfType = pTypeInfo->kindOfType;
        userType->_activator = pTypeInfo->activator;
        userType->_collectionAdd = pTypeInfo->collectionAdd;
        userType->_dictionaryAdd = pTypeInfo->dictionaryAdd;
        userType->_fromStringConverter = pTypeInfo->fromStringConverter;
        userType->ContentPropertyName(pTypeInfo->contentPropertyName);
        userType->IsLocalType(pTypeInfo->flags & TypeInfo_Flags_IsLocalType);
        userType->IsReturnTypeStub(pTypeInfo->flags & TypeInfo_Flags_IsReturnTypeStub);
        userType->IsBindable(pTypeInfo->flags & TypeInfo_Flags_IsBindable);
        userType->IsMarkupExtension(pTypeInfo->flags & TypeInfo_Flags_IsMarkupExtension);
        userType->_createFromStringMethod = nullptr;
        userType->SetBoxedType(GetXamlTypeByName(boxedName));
        for (int i = pTypeInfo->firstMemberIndex; i < pNextTypeInfo->firstMemberIndex; ++i)
        {
            userType->AddMemberName(MemberInfos[i].shortName);
        }
        for (int i = pTypeInfo->firstEnumValueIndex; i < pNextTypeInfo->firstEnumValueIndex; ++i)
        {
            userType->AddEnumValue(EnumValues[i].name, winrt::Windows::Foundation::PropertyValue::CreateInt32(EnumValues[i].eValue));
        }
        return userType.as<IXamlType>();
    }
}

IXamlMember XamlTypeInfoProvider::CreateXamlMember(::winrt::hstring const& longMemberName)
{
    const MemberInfo* pMemberInfo = GetMemberInfo(longMemberName);
    if (!pMemberInfo)
    {
        return nullptr;
    }
    auto xamlMember = ::winrt::make_self<XamlMember>(shared_from_this(),
        pMemberInfo->shortName, TypeInfos[pMemberInfo->typeIndex].typeName);
    xamlMember->_getter = pMemberInfo->getter;
    xamlMember->_setter = pMemberInfo->setter;
    xamlMember->TargetTypeName(pMemberInfo->targetTypeIndex >= 0 ? TypeInfos[pMemberInfo->targetTypeIndex].typeName : L"");
    xamlMember->IsReadOnly(pMemberInfo->isReadOnly);
    xamlMember->IsDependencyProperty(pMemberInfo->isDependencyProperty);
    xamlMember->IsAttachable(pMemberInfo->isAttachable);

    return xamlMember.as<IXamlMember>();
}
} // namespace
